//! Flags and variables a fresh save starts with.
//!
//! [`RESET_MAP_FLAGS`] holds the `setflag` operands of
//! `EventScript_ResetAllMapFlags` (`pokeemerald/data/scripts/new_game.inc:116-274`,
//! run from `NewGameInitData`, `pokeemerald/src/new_game.c:196`). The
//! `setberrytree` calls that follow it (`EventScript_ResetAllBerries`,
//! `new_game.inc:1-113`) are not part of this table.
//!
//! The `TRUCK_INTRO_*` tables are the flags and variables the moving-truck
//! exit sets for each player gender, for a start that skips the truck.

/// Hides the rival's bedroom object event in Brendan's house
/// (`pokeemerald/include/constants/flags.h:811`).
pub const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM: u16 = 0x2F8;

const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM: u16 = 0x2F7;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK: u16 = 0x2FA;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM: u16 = 0x310;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_SIBLING: u16 = 0x2DF;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL: u16 = 0x331;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM: u16 = 0x2F6;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK: u16 = 0x2F9;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM: u16 = 0x311;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING: u16 = 0x2E0;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL: u16 = 0x332;
const FLAG_HIDE_CONTEST_POKE_BALL: u16 = 0x56;
const FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE: u16 = 0x301;
const FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE: u16 = 0x302;
const FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE: u16 = 0x303;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH: u16 = 0x2D1;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL: u16 = 0x379;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CYNDAQUIL: u16 = 0x32B;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_TOTODILE: u16 = 0x32C;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CHIKORITA: u16 = 0x346;
const FLAG_HIDE_PETALBURG_CITY_WALLY: u16 = 0x2D6;
const FLAG_UNKNOWN_363: u16 = 0x363;
const FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT: u16 = 0x2DB;
const FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1: u16 = 0x2DC;
const FLAG_HIDE_RUSTBORO_CITY_RIVAL: u16 = 0x32E;
const FLAG_HIDE_RUSTBORO_CITY_SCIENTIST: u16 = 0x34C;
const FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN: u16 = 0x364;
const FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY: u16 = 0x2E3;
const FLAG_HIDE_BRINEYS_HOUSE_PEEKO: u16 = 0x371;
const FLAG_HIDE_ROUTE_104_MR_BRINEY: u16 = 0x2E2;
const FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN: u16 = 0x2E4;
const FLAG_HIDE_ROUTE_109_MR_BRINEY: u16 = 0x2E5;
const FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN: u16 = 0x2E7;
const FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT: u16 = 0x2E8;
const FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST: u16 = 0x38A;
const FLAG_HIDE_ROUTE_110_BIRCH: u16 = 0x345;
const FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1: u16 = 0x306;
const FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_2: u16 = 0x37F;
const FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1: u16 = 0x308;
const FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2: u16 = 0x309;
const FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3: u16 = 0x30A;
const FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4: u16 = 0x30B;
const FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS: u16 = 0x30C;
const FLAG_HIDE_PETALBURG_GYM_GREETER: u16 = 0x30D;
const FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD: u16 = 0x338;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN: u16 = 0x2E9;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY: u16 = 0x2EA;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM: u16 = 0x2D2;
const FLAG_HIDE_PLAYERS_HOUSE_DAD: u16 = 0x2DE;
const FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL: u16 = 0x351;
const FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL: u16 = 0x32F;
const FLAG_HIDE_FANCLUB_OLD_LADY: u16 = 0x315;
const FLAG_HIDE_FANCLUB_BOY: u16 = 0x316;
const FLAG_HIDE_FANCLUB_LITTLE_BOY: u16 = 0x317;
const FLAG_HIDE_FANCLUB_LADY: u16 = 0x318;
const FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER: u16 = 0x2DA;
const FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1: u16 = 0x31D;
const FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1: u16 = 0x31E;
const FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2: u16 = 0x31F;
const FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2: u16 = 0x385;
const FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2: u16 = 0x386;
const FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3: u16 = 0x387;
const FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3: u16 = 0x388;
const FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER: u16 = 0x323;
const FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER: u16 = 0x322;
const FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY: u16 = 0x326;
const FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDAS_BOYFRIEND: u16 = 0x328;
const FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE: u16 = 0x329;
const FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDA: u16 = 0x3D8;
const FLAG_HIDE_VERDANTURF_TOWN_SCOTT: u16 = 0x2FE;
const FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD: u16 = 0x33E;
const FLAG_HIDE_PETALBURG_GYM_WALLY: u16 = 0x362;
const FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY: u16 = 0x365;
const FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE: u16 = 0x33C;
const FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE: u16 = 0x33D;
const FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS: u16 = 0x33F;
const FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE: u16 = 0x35B;
const FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON: u16 = 0x355;
const FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN: u16 = 0x349;
const FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT: u16 = 0x34D;
const FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE: u16 = 0x34E;
const FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL: u16 = 0x35C;
const FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL: u16 = 0x35D;
const FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY: u16 = 0x343;
const FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN: u16 = 0x348;
const FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW: u16 = 0x350;
const FLAG_HIDE_ROUTE_119_RIVAL: u16 = 0x353;
const FLAG_HIDE_ROUTE_119_SCOTT: u16 = 0x312;
const FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN: u16 = 0x3CD;
const FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE: u16 = 0x330;
const FLAG_HIDE_LANETTES_HOUSE_LANETTE: u16 = 0x366;
const FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN: u16 = 0x368;
const FLAG_HIDE_MT_CHIMNEY_TRAINERS: u16 = 0x36D;
const FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY: u16 = 0x3E2;
const FLAG_HIDE_RUSTURF_TUNNEL_BRINEY: u16 = 0x36F;
const FLAG_HIDE_ROUTE_116_MR_BRINEY: u16 = 0x37B;
const FLAG_HIDE_RUSTURF_TUNNEL_PEEKO: u16 = 0x370;
const FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT: u16 = 0x36E;
const FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND: u16 = 0x327;
const FLAG_HIDE_RUSTURF_TUNNEL_WANDA: u16 = 0x3D7;
const FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE: u16 = 0x376;
const FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1: u16 = 0x374;
const FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2: u16 = 0x375;
const FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION: u16 = 0x3C1;
const FLAG_HIDE_BATTLE_TOWER_OPPONENT: u16 = 0x378;
const FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE: u16 = 0x2F0;
const FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_BEDROOM_MOM: u16 = 0x2F5;
const FLAG_HIDE_LITTLEROOT_TOWN_RIVAL: u16 = 0x31A;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCH: u16 = 0x31B;
const FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS: u16 = 0x37C;
const FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_UNKNOWN_380: u16 = 0x380;
const FLAG_HIDE_ROUTE_101_BIRCH: u16 = 0x381;
const FLAG_HIDE_ROUTE_103_BIRCH: u16 = 0x382;
const FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR: u16 = 0x38D;
const FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER: u16 = 0x2EC;
const FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE: u16 = 0x38E;
const FLAG_HIDE_SOUTHERN_ISLAND_UNCHOSEN_EON_DUO_MON: u16 = 0x38F;
const FLAG_UNKNOWN_393: u16 = 0x393;
const FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE: u16 = 0x358;
const FLAG_HIDE_MAUVILLE_CITY_WATTSON: u16 = 0x390;
const FLAG_HIDE_MAUVILLE_CITY_SCOTT: u16 = 0x2FD;
const FLAG_HIDE_CHAMPIONS_ROOM_RIVAL: u16 = 0x398;
const FLAG_HIDE_CHAMPIONS_ROOM_BIRCH: u16 = 0x399;
const FLAG_HIDE_ROUTE_110_RIVAL_ON_BIKE: u16 = 0x39A;
const FLAG_HIDE_ROUTE_119_RIVAL_ON_BIKE: u16 = 0x39B;
const FLAG_HIDE_ROUTE_104_RIVAL: u16 = 0x2CF;
const FLAG_HIDE_LILYCOVE_MOTEL_GAME_DESIGNERS: u16 = 0x39D;
const FLAG_HIDE_LAVARIDGE_TOWN_RIVAL: u16 = 0x3A1;
const FLAG_HIDE_LAVARIDGE_TOWN_RIVAL_ON_BIKE: u16 = 0x3A2;
const FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL: u16 = 0x3A6;
const FLAG_HIDE_METEOR_FALLS_TEAM_AQUA: u16 = 0x3AA;
const FLAG_HIDE_DEWFORD_HALL_SLUDGE_BOMB_MAN: u16 = 0x3AC;
const FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO: u16 = 0x3A0;
const FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M: u16 = 0x3E0;
const FLAG_HIDE_ROUTE_128_STEVEN: u16 = 0x342;
const FLAG_HIDE_ROUTE_128_ARCHIE: u16 = 0x3B0;
const FLAG_HIDE_ROUTE_128_MAXIE: u16 = 0x3B1;
const FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE: u16 = 0x3B3;
const FLAG_HIDE_SLATEPORT_CITY_TM_SALESMAN: u16 = 0x3B4;
const FLAG_HIDE_SLATEPORT_CITY_SCOTT: u16 = 0x2ED;
const FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY: u16 = 0x35A;
const FLAG_HIDE_VICTORY_ROAD_EXIT_WALLY: u16 = 0x2EF;
const FLAG_HIDE_SS_TIDAL_CORRIDOR_MR_BRINEY: u16 = 0x3B6;
const FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN: u16 = 0x3C7;
const FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL: u16 = 0x3C8;
const FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_INVISIBLE_NINJA_BOY: u16 = 0x2D7;
const FLAG_HIDE_OLDALE_TOWN_RIVAL: u16 = 0x3D3;
const FLAG_HIDE_ROUTE_101_BOY: u16 = 0x3DF;
const FLAG_HIDE_PETALBURG_CITY_SCOTT: u16 = 0x3E3;
const FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA: u16 = 0x3E4;
const FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE: u16 = 0x3E5;
const FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON: u16 = 0x3E6;
const FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS: u16 = 0x356;
const FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE: u16 = 0x33A;
const FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE: u16 = 0x33B;
const FLAG_HIDE_ROUTE_111_DESERT_FOSSIL: u16 = 0x36C;
const FLAG_HIDE_ROUTE_111_PLAYER_DESCENT: u16 = 0x36B;
const FLAG_HIDE_DESERT_UNDERPASS_FOSSIL: u16 = 0x36A;
const FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA: u16 = 0x337;
const FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA: u16 = 0x2F4;
const FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA: u16 = 0x35E;
const FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN: u16 = 0x35F;
const FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER: u16 = 0x340;
const FLAG_HIDE_DEOXYS: u16 = 0x2FB;
const FLAG_HIDE_SAFARI_ZONE_SOUTH_EAST_EXPANSION: u16 = 0x2EB;
const FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT: u16 = 0x2FF;
const FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT: u16 = 0x319;
const FLAG_HIDE_SKY_PILLAR_WALLACE: u16 = 0x357;
const FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL: u16 = 0x50;

/// Flags set by the male branch of `InsideOfTruck_EventScript_SetIntroFlags`
/// (`pokeemerald/data/maps/InsideOfTruck/scripts.inc:24-35`), in script order.
///
/// Upstream sets these when the player leaves the truck, not from
/// `NewGameInitData`; a start that bypasses the truck must apply them itself
/// or the rival's belongings and family stay visible in the player's house.
#[rustfmt::skip]
pub const TRUCK_INTRO_FLAGS_MALE: &[u16] = &[
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_SIBLING,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL,
];

/// Flags set by the female branch of `InsideOfTruck_EventScript_SetIntroFlags`
/// (`pokeemerald/data/maps/InsideOfTruck/scripts.inc:37-48`), in script order.
/// Same shape as [`TRUCK_INTRO_FLAGS_MALE`] with Brendan and May swapped.
#[rustfmt::skip]
pub const TRUCK_INTRO_FLAGS_FEMALE: &[u16] = &[
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL,
];

const VAR_LITTLEROOT_INTRO_STATE: u16 = 0x4092;
const VAR_LITTLEROOT_HOUSES_STATE_BRENDAN: u16 = 0x408C;
const VAR_LITTLEROOT_HOUSES_STATE_MAY: u16 = 0x4082;

const INTRO_STATE_MALE_LEFT_TRUCK: u16 = 1;
const INTRO_STATE_FEMALE_LEFT_TRUCK: u16 = 2;
const HOUSES_STATE_AFTER_TRUCK: u16 = 1;

/// `(variable ID, value)` pairs set by the male branch
/// (`pokeemerald/data/maps/InsideOfTruck/scripts.inc:26,32`). The intro-state
/// variable is also the truck trigger's guard, so setting it makes the effect
/// once-only.
pub const TRUCK_INTRO_VARS_MALE: &[(u16, u16)] = &[
    (VAR_LITTLEROOT_INTRO_STATE, INTRO_STATE_MALE_LEFT_TRUCK),
    (
        VAR_LITTLEROOT_HOUSES_STATE_BRENDAN,
        HOUSES_STATE_AFTER_TRUCK,
    ),
];

/// `(variable ID, value)` pairs set by the female branch
/// (`pokeemerald/data/maps/InsideOfTruck/scripts.inc:39,45`).
pub const TRUCK_INTRO_VARS_FEMALE: &[(u16, u16)] = &[
    (VAR_LITTLEROOT_INTRO_STATE, INTRO_STATE_FEMALE_LEFT_TRUCK),
    (VAR_LITTLEROOT_HOUSES_STATE_MAY, HOUSES_STATE_AFTER_TRUCK),
];

/// The 159 `setflag` operands of `EventScript_ResetAllMapFlags`, in script
/// order (module docs). Every id is below `engine::event_data::FLAGS_COUNT`.
///
/// `FLAG_UNKNOWN_0x363` and `FLAG_UNKNOWN_0x393` are unnamed upstream
/// (`pokeemerald/include/constants/flags.h:918,966`: "Set, however has no
/// purpose"); they are kept because the script sets them.
#[rustfmt::skip]
pub const RESET_MAP_FLAGS: &[u16] = &[
    FLAG_HIDE_CONTEST_POKE_BALL,
    FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE,
    FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE,
    FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CYNDAQUIL,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_TOTODILE,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CHIKORITA,
    FLAG_HIDE_PETALBURG_CITY_WALLY,
    FLAG_UNKNOWN_363,
    FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT,
    FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1,
    FLAG_HIDE_RUSTBORO_CITY_RIVAL,
    FLAG_HIDE_RUSTBORO_CITY_SCIENTIST,
    FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN,
    FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY,
    FLAG_HIDE_BRINEYS_HOUSE_PEEKO,
    FLAG_HIDE_ROUTE_104_MR_BRINEY,
    FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN,
    FLAG_HIDE_ROUTE_109_MR_BRINEY,
    FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN,
    FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT,
    FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST,
    FLAG_HIDE_ROUTE_110_BIRCH,
    FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1,
    FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_2,
    FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1,
    FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2,
    FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3,
    FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4,
    FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS,
    FLAG_HIDE_PETALBURG_GYM_GREETER,
    FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM,
    FLAG_HIDE_PLAYERS_HOUSE_DAD,
    FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL,
    FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL,
    FLAG_HIDE_FANCLUB_OLD_LADY,
    FLAG_HIDE_FANCLUB_BOY,
    FLAG_HIDE_FANCLUB_LITTLE_BOY,
    FLAG_HIDE_FANCLUB_LADY,
    FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER,
    FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1,
    FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1,
    FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2,
    FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2,
    FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2,
    FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3,
    FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3,
    FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER,
    FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER,
    FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY,
    FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDAS_BOYFRIEND,
    FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE,
    FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDA,
    FLAG_HIDE_VERDANTURF_TOWN_SCOTT,
    FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD,
    FLAG_HIDE_PETALBURG_GYM_WALLY,
    FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE,
    FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL,
    FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL,
    FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY,
    FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW,
    FLAG_HIDE_ROUTE_119_RIVAL,
    FLAG_HIDE_ROUTE_119_SCOTT,
    FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN,
    FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE,
    FLAG_HIDE_LANETTES_HOUSE_LANETTE,
    FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN,
    FLAG_HIDE_MT_CHIMNEY_TRAINERS,
    FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY,
    FLAG_HIDE_RUSTURF_TUNNEL_BRINEY,
    FLAG_HIDE_ROUTE_116_MR_BRINEY,
    FLAG_HIDE_RUSTURF_TUNNEL_PEEKO,
    FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT,
    FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND,
    FLAG_HIDE_RUSTURF_TUNNEL_WANDA,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2,
    FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION,
    FLAG_HIDE_BATTLE_TOWER_OPPONENT,
    FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE,
    FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_BEDROOM_MOM,
    FLAG_HIDE_LITTLEROOT_TOWN_RIVAL,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCH,
    FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS,
    FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_UNKNOWN_380,
    FLAG_HIDE_ROUTE_101_BIRCH,
    FLAG_HIDE_ROUTE_103_BIRCH,
    FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR,
    FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER,
    FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE,
    FLAG_HIDE_SOUTHERN_ISLAND_UNCHOSEN_EON_DUO_MON,
    FLAG_UNKNOWN_393,
    FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE,
    FLAG_HIDE_MAUVILLE_CITY_WATTSON,
    FLAG_HIDE_MAUVILLE_CITY_SCOTT,
    FLAG_HIDE_CHAMPIONS_ROOM_RIVAL,
    FLAG_HIDE_CHAMPIONS_ROOM_BIRCH,
    FLAG_HIDE_ROUTE_110_RIVAL_ON_BIKE,
    FLAG_HIDE_ROUTE_119_RIVAL_ON_BIKE,
    FLAG_HIDE_ROUTE_104_RIVAL,
    FLAG_HIDE_LILYCOVE_MOTEL_GAME_DESIGNERS,
    FLAG_HIDE_LAVARIDGE_TOWN_RIVAL,
    FLAG_HIDE_LAVARIDGE_TOWN_RIVAL_ON_BIKE,
    FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL,
    FLAG_HIDE_METEOR_FALLS_TEAM_AQUA,
    FLAG_HIDE_DEWFORD_HALL_SLUDGE_BOMB_MAN,
    FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO,
    FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M,
    FLAG_HIDE_ROUTE_128_STEVEN,
    FLAG_HIDE_ROUTE_128_ARCHIE,
    FLAG_HIDE_ROUTE_128_MAXIE,
    FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE,
    FLAG_HIDE_SLATEPORT_CITY_TM_SALESMAN,
    FLAG_HIDE_SLATEPORT_CITY_SCOTT,
    FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY,
    FLAG_HIDE_VICTORY_ROAD_EXIT_WALLY,
    FLAG_HIDE_SS_TIDAL_CORRIDOR_MR_BRINEY,
    FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN,
    FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL,
    FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_INVISIBLE_NINJA_BOY,
    FLAG_HIDE_OLDALE_TOWN_RIVAL,
    FLAG_HIDE_ROUTE_101_BOY,
    FLAG_HIDE_PETALBURG_CITY_SCOTT,
    FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA,
    FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE,
    FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON,
    FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS,
    FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE,
    FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE,
    FLAG_HIDE_ROUTE_111_DESERT_FOSSIL,
    FLAG_HIDE_ROUTE_111_PLAYER_DESCENT,
    FLAG_HIDE_DESERT_UNDERPASS_FOSSIL,
    FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN,
    FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER,
    FLAG_HIDE_DEOXYS,
    FLAG_HIDE_SAFARI_ZONE_SOUTH_EAST_EXPANSION,
    FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT,
    FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT,
    FLAG_HIDE_SKY_PILLAR_WALLACE,
    FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL,
];
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reset_map_flags_has_the_upstream_count() {
        assert_eq!(RESET_MAP_FLAGS.len(), 159);
    }

    /// `engine::event_data::FLAGS_COUNT`; `assets` cannot depend on `engine`.
    const ORDINARY_FLAGS_END: u16 = 0x960;

    #[test]
    fn reset_map_flags_are_all_ordinary_ids() {
        for &id in RESET_MAP_FLAGS {
            assert!(
                id < ORDINARY_FLAGS_END,
                "flag id {id:#X} outside the ordinary range"
            );
        }
    }

    /// Direct diagnostics for notable entries; the entry-for-entry test below
    /// pins the whole table.
    #[test]
    fn reset_map_flags_spot_checks_match_flags_h() {
        assert_eq!(RESET_MAP_FLAGS[0], FLAG_HIDE_CONTEST_POKE_BALL);
        assert_eq!(RESET_MAP_FLAGS[10], FLAG_UNKNOWN_363);
        assert_eq!(
            RESET_MAP_FLAGS[36],
            FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM
        );
        assert_eq!(RESET_MAP_FLAGS[107], FLAG_UNKNOWN_393);
        assert_eq!(
            RESET_MAP_FLAGS[134],
            FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL
        );
        assert_eq!(RESET_MAP_FLAGS[153], FLAG_HIDE_DEOXYS);
        // The last `setflag` before `call EventScript_ResetAllBerries`
        // (`new_game.inc:274`).
        assert_eq!(
            RESET_MAP_FLAGS[158],
            FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL
        );
    }

    /// The `setflag` operands of `EventScript_ResetAllMapFlags`
    /// (`data/scripts/new_game.inc:116-274`), transcribed independently of
    /// [`RESET_MAP_FLAGS`] by looking each `FLAG_*` up in `flags.h`.
    #[rustfmt::skip]
    const UPSTREAM_SETFLAG_OPERANDS: [u16; 159] = [
        0x056, 0x301, 0x302, 0x303, 0x2D1, 0x379, 0x32B, 0x32C,
        0x346, 0x2D6, 0x363, 0x2DB, 0x2DC, 0x32E, 0x34C, 0x364,
        0x2E3, 0x371, 0x2E2, 0x2E4, 0x2E5, 0x2E7, 0x2E8, 0x38A,
        0x345, 0x306, 0x37F, 0x308, 0x309, 0x30A, 0x30B, 0x30C,
        0x30D, 0x338, 0x2E9, 0x2EA, 0x2F8, 0x2D2, 0x2DE, 0x351,
        0x32F, 0x315, 0x316, 0x317, 0x318, 0x2DA, 0x31D, 0x31E,
        0x31F, 0x385, 0x386, 0x387, 0x388, 0x323, 0x322, 0x326,
        0x328, 0x329, 0x3D8, 0x2FE, 0x33E, 0x362, 0x365, 0x33C,
        0x33D, 0x33F, 0x35B, 0x355, 0x349, 0x34D, 0x34E, 0x35C,
        0x35D, 0x343, 0x348, 0x350, 0x353, 0x312, 0x3CD, 0x330,
        0x366, 0x368, 0x36D, 0x3E2, 0x36F, 0x37B, 0x370, 0x36E,
        0x327, 0x3D7, 0x376, 0x374, 0x375, 0x3C1, 0x378, 0x2F0,
        0x2F5, 0x31A, 0x31B, 0x37C, 0x380, 0x381, 0x382, 0x38D,
        0x2EC, 0x38E, 0x38F, 0x393, 0x358, 0x390, 0x2FD, 0x398,
        0x399, 0x39A, 0x39B, 0x2CF, 0x39D, 0x3A1, 0x3A2, 0x3A6,
        0x3AA, 0x3AC, 0x3A0, 0x3E0, 0x342, 0x3B0, 0x3B1, 0x3B3,
        0x3B4, 0x2ED, 0x35A, 0x2EF, 0x3B6, 0x3C7, 0x3C8, 0x2D7,
        0x3D3, 0x3DF, 0x3E3, 0x3E4, 0x3E5, 0x3E6, 0x356, 0x33A,
        0x33B, 0x36C, 0x36B, 0x36A, 0x337, 0x2F4, 0x35E, 0x35F,
        0x340, 0x2FB, 0x2EB, 0x2FF, 0x319, 0x357, 0x050,
    ];

    #[test]
    fn reset_map_flags_match_the_upstream_script_entry_for_entry() {
        assert_eq!(
            RESET_MAP_FLAGS.len(),
            UPSTREAM_SETFLAG_OPERANDS.len(),
            "one entry per upstream `setflag`"
        );
        for (i, (&got, &want)) in RESET_MAP_FLAGS
            .iter()
            .zip(UPSTREAM_SETFLAG_OPERANDS.iter())
            .enumerate()
        {
            assert_eq!(
                got, want,
                "RESET_MAP_FLAGS[{i}] is {got:#X}, but upstream setflag #{i} \
                 is {want:#X}"
            );
        }
    }

    #[test]
    fn reset_map_flags_has_no_duplicate_ids() {
        let mut sorted = RESET_MAP_FLAGS.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), RESET_MAP_FLAGS.len());
    }

    #[test]
    fn rival_bedroom_flag_is_in_the_reset_list() {
        assert!(RESET_MAP_FLAGS.contains(&FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM));
    }

    /// [`crate::object_event_flags`] transcribes these ids independently, so
    /// agreement checks both transcriptions.
    #[test]
    fn truck_intro_flags_agree_with_the_object_event_flag_table() {
        use crate::object_event_flags::resolve;
        let male = [
            "FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM",
            "FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK",
            "FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM",
            "FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_SIBLING",
            "FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL",
        ];
        let female = [
            "FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM",
            "FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK",
            "FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM",
            "FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING",
            "FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL",
        ];
        for (names, ids) in [
            (male, TRUCK_INTRO_FLAGS_MALE),
            (female, TRUCK_INTRO_FLAGS_FEMALE),
        ] {
            assert_eq!(names.len(), ids.len(), "one setflag per script line");
            for (name, &id) in names.iter().zip(ids) {
                assert_eq!(resolve(name), Some(id), "{name} disagrees, in script order");
            }
        }
    }

    #[test]
    fn truck_intro_branches_have_unique_disjoint_flags_and_matching_var_shapes() {
        assert_eq!(TRUCK_INTRO_FLAGS_MALE.len(), TRUCK_INTRO_FLAGS_FEMALE.len());
        for id in TRUCK_INTRO_FLAGS_MALE {
            assert!(
                !TRUCK_INTRO_FLAGS_FEMALE.contains(id),
                "{id:#x} cannot belong to both gender branches"
            );
        }
        for ids in [TRUCK_INTRO_FLAGS_MALE, TRUCK_INTRO_FLAGS_FEMALE] {
            let mut sorted = ids.to_vec();
            sorted.sort_unstable();
            sorted.dedup();
            assert_eq!(sorted.len(), ids.len(), "no duplicates within a branch");
        }

        assert_eq!(TRUCK_INTRO_VARS_MALE.len(), TRUCK_INTRO_VARS_FEMALE.len());
        assert_eq!(TRUCK_INTRO_VARS_MALE[0].0, TRUCK_INTRO_VARS_FEMALE[0].0);
        assert_ne!(TRUCK_INTRO_VARS_MALE[0].1, TRUCK_INTRO_VARS_FEMALE[0].1);
    }

    #[test]
    fn no_truck_intro_flag_is_already_a_reset_map_flag() {
        for ids in [TRUCK_INTRO_FLAGS_MALE, TRUCK_INTRO_FLAGS_FEMALE] {
            for id in ids {
                assert!(
                    !RESET_MAP_FLAGS.contains(id),
                    "{id:#x} is in both EventScript_ResetAllMapFlags and the truck intro"
                );
            }
        }
    }
}
