//! ROM import (S-4, F-3, Discussion #71 policy C, issue #122): turn a
//! user-supplied Pokemon Emerald cartridge image into an asset pack.
//!
//! Policy A extracts assets from a `pokeemerald` decomp checkout, which
//! needs a toolchain and a clone. Policy C asks the player for the one thing
//! they already have to play the game legally, their own ROM, and reads the
//! assets straight out of it. Both feed the same
//! [`pack_format`] layout with the same normalized asset ids, so nothing
//! downstream of the pack can tell which produced it.
//!
//! The importer supports exactly one build: Pokemon Emerald, US, revision 0,
//! SHA-1 `f3ae088181bf583e55daf962a92bb46f4f1d07b7`, game code `BPEE`,
//! version 0, exactly 16 MiB. Identity is the whole-file hash and nothing
//! else. See [`profile`] for why.
//!
//! # What exists
//!
//! The ROM-side foundation, and the domain readers built on it:
//!
//! - [`Rom`] loads and validates an image: exact size, GBA cartridge header
//!   with its fixed byte and complement check, whole-file SHA-1.
//! - [`RomReader`] and [`GbaPtr`] read it. Every read is bounds-checked and
//!   every address computation is checked arithmetic, so a garbage pointer
//!   is a typed error naming the offset, never a panic.
//! - [`lz77_decompress`] unpacks the GBA BIOS LZ77 streams most bulk data is
//!   stored in.
//! - [`select_profile`] picks a [`RevisionProfile`] by SHA-1 alone, then
//!   corroborates the header.
//! - [`Roots`] is that profile's address table, generated by `cargo xtask
//!   gen-rom-profile` into [`profiles::bpee_rev0`]. It covers every asset
//!   domain the pack holds: tilesets and their animations, the title
//!   screen, object-event sprites, map layouts, fonts, text windows,
//!   interface palettes, and `MUS_TITLE`'s audio tree.
//! - [`Sha1`] is a hand-rolled FIPS 180-4 implementation, because the hash
//!   is needed and a dependency is not `(minimal-deps)`.
//! - [`fixture::RomFixture`] builds synthetic ROM-shaped images for tests.
//!   No real ROM is ever needed to test this crate.
//! - `domains` holds one reader per asset domain. Every graphics domain is
//!   wired: the title screen (`title/image/*`, `title/raw/*`,
//!   `title/palette/*`), the interface palettes (`interface/palette/*`),
//!   the tilesets (`tileset/*`: tile sheets, palette banks, metatile
//!   tables, animation frames), the map layouts (`layout/*`: metatile grids
//!   and border blocks), the object-event sprites (`sprite/*` sheets and
//!   `sprite/palette/*` banks), the Latin glyph sheets (`font/*/glyphs`,
//!   decoded from `gbagfx`'s `.latfont` layout), and the text windows
//!   (`text-window/image/*`, `text-window/palette/*`). The sound engine's
//!   data is wired too: `DirectSound` samples and programmable waves
//!   (`audio/sample/*`) and voicegroups (`audio/voicegroup/*`), read from
//!   the m4a `WaveData` and `ToneData` structs and emitted through
//!   `assets`' own schema encoders, and `MUS_TITLE` itself
//!   (`audio/song/*`), decoded from the engine's track byte-code into
//!   `assets::Song` events. A domain that has a ROM struct behind
//!   its roots corroborates it field by field, so a wrong profile is a
//!   typed error rather than a plausible-looking asset. [`import`] and
//!   [`import_to_bytes`] run them into a `PackWriter` and hand back a real
//!   pack.
//!
//! # Equivalence
//!
//! The pack this crate writes has to be byte-identical to the one `cargo
//! xtask extract` writes from a decomp checkout, for every id both produce.
//! `tests/equivalence.rs` is that gate: it is `#[ignore]`d, needs
//! `$POKEEMERALD_ROM` and a checkout pack, and compares the two packs entry
//! by entry. Every id the checkout pack holds is covered and there is no
//! reviewed difference.
//!
//! `pokeemerald-rs --import-rom` (that crate's `cli` and `import_rom`
//! modules) drives [`import`] and surfaces this crate's errors as they
//! are; the player-facing walkthrough is the top-level README's "Playing"
//! section.

pub mod fixture;
pub mod profiles;

mod domains;
mod error;
mod lz77;
mod one_line;
mod profile;
mod reader;
mod rom;
mod roots;
mod sha1;

use std::path::{Path, PathBuf};

pub use error::{HeaderFault, ImportError, Lz77Fault, PartialFile, SongFault};
pub use lz77::{decompress as lz77_decompress, decompress_at as lz77_decompress_at, LZ77_TYPE};
pub use one_line::{OneLine, OneLinePath};
pub use profile::{
    select as select_profile, select_with as select_profile_with, RevisionProfile, EMERALD_US_REV0,
    KNOWN_PROFILES,
};
pub use reader::{GbaPtr, RomReader, ROM_BASE, ROM_WINDOW_END};
pub use rom::{GbaHeader, Rom, ROM_SIZE};
pub use roots::{
    AudioRoots, BlobRoot, Encoding, FontRoot, ImageRoot, InterfaceRoots, KeysplitRoot,
    MapLayoutRoot, PaletteRoot, Roots, SampleRoot, SongRoot, SpriteRoots, TextWindowRoots,
    TileAnimRoot, TilesetRoot, TitleScreenRoots, VoicegroupRoot,
};
pub use sha1::{sha1, Digest, DigestParseError, Sha1};

/// What an import produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportReport {
    pack_path: PathBuf,
    profile: &'static str,
    entry_count: usize,
    pack_bytes: usize,
}

impl ImportReport {
    /// Record one import's result.
    #[must_use]
    pub const fn new(
        pack_path: PathBuf,
        profile: &'static str,
        entry_count: usize,
        pack_bytes: usize,
    ) -> Self {
        Self {
            pack_path,
            profile,
            entry_count,
            pack_bytes,
        }
    }

    /// Where the pack was written.
    #[must_use]
    pub fn pack_path(&self) -> &Path {
        &self.pack_path
    }

    /// The name of the profile the ROM matched.
    #[must_use]
    pub const fn profile(&self) -> &'static str {
        self.profile
    }

    /// How many entries the pack holds.
    #[must_use]
    pub const fn entry_count(&self) -> usize {
        self.entry_count
    }

    /// How large the pack is, in bytes.
    #[must_use]
    pub const fn pack_bytes(&self) -> usize {
        self.pack_bytes
    }
}

/// A finished pack the caller has yet to put anywhere.
///
/// [`import_pack`] and [`import_pack_from_file`] hand one back so a caller
/// that publishes the pack itself does not have to re-parse the bytes to
/// learn what they hold. `pokeemerald-rs`'s `--import-rom` is that caller:
/// it creates the file and renames it into place against a directory
/// descriptor it holds open, which no API taking an output *path* can do on
/// its behalf — and it opens the ROM itself, which is why the handle-taking
/// form exists.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportedPack {
    entry_count: usize,
    bytes: Vec<u8>,
}

impl ImportedPack {
    /// A pack of `bytes` holding `entry_count` entries.
    ///
    /// Public for the same reason [`ImportReport::new`] is: a caller's
    /// tests stand in for the importer without a real ROM.
    #[must_use]
    pub const fn new(entry_count: usize, bytes: Vec<u8>) -> Self {
        Self { entry_count, bytes }
    }

    /// How many entries the pack holds.
    #[must_use]
    pub const fn entry_count(&self) -> usize {
        self.entry_count
    }

    /// The serialized pack.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// The serialized pack, owned.
    #[must_use]
    pub fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }
}

/// Import the ROM at `rom_path` into an asset pack at `out_path`.
///
/// Builds the whole pack in memory first, so a failure part-way through a
/// domain cannot leave a truncated file behind, then creates `out_path`
/// and writes it.
///
/// This is the path-level API. A caller that has to publish the pack
/// through a directory it holds open — `pokeemerald-rs`'s `--import-rom`,
/// whose destination the player picks — takes the bytes from
/// [`import_pack`] and owns the file itself.
///
/// The ROM is never a legal destination: it is read whole into memory
/// first, so writing the pack over it would succeed and destroy the
/// player's cartridge image. That is [`ImportError::SameFile`], raised
/// before anything is written.
///
/// Neither is a path that already exists. `out_path` is a file this call
/// creates, exclusively, so a link planted at that name is refused rather
/// than followed and truncated (`write_new`); the caller publishes the
/// finished file over the real destination itself.
///
/// A write that dies part-way leaves the partial file this call created at
/// `out_path` in place off Windows, reported as [`PartialFile::MayRemain`]
/// on the returned [`ImportError::WriteFailed`]; a retry on that name is
/// refused (`AlreadyExists`) until it is cleared. On Windows the confirmed
/// file is deleted instead ([`PartialFile::Gone`]), and a retry lands at
/// the same name. `source` stays the write's own I/O failure either way. A
/// replacement a concurrent writer put there is left alone everywhere,
/// within the bound `classify_partial_file` states.
///
/// # Errors
///
/// [`ImportError::ReadFailed`], [`ImportError::WrongSize`], or
/// [`ImportError::BadHeader`] if the file is not a GBA ROM;
/// [`ImportError::SameFile`] if `out_path` names the ROM itself;
/// [`ImportError::UnsupportedRevision`] if it is not the supported build;
/// anything a domain reader raises (see [`import_to_bytes`]);
/// [`ImportError::WriteFailed`] if the finished pack cannot be written,
/// which includes a destination that already exists.
pub fn import(rom_path: &Path, out_path: &Path) -> Result<ImportReport, ImportError> {
    let rom = Rom::load(rom_path)?;
    // Ahead of the revision check: which file gets clobbered does not
    // depend on which ROM it is, and naming the destructive mistake is
    // more use to the player than naming the wrong revision.
    if overwrites_rom(rom_path, out_path) {
        return Err(ImportError::SameFile {
            path: out_path.to_path_buf(),
        });
    }
    let profile = select_profile(&rom)?;
    let (entry_count, bytes) = build_pack(&rom, &profile.roots)?;
    write_new(out_path, &bytes).map_err(|failure| failure.at(out_path))?;
    Ok(ImportReport::new(
        out_path.to_path_buf(),
        profile.name,
        entry_count,
        bytes.len(),
    ))
}

/// Import the ROM at `rom_path` and hand back the finished pack.
///
/// [`import`] without the write, and the entry point for a caller that
/// publishes the pack itself: the ROM is never touched for writing here,
/// so there is no destination to guard.
///
/// # Errors
///
/// As [`import`], minus [`ImportError::WriteFailed`] and
/// [`ImportError::SameFile`]. A domain reader adds
/// [`ImportError::Truncated`] or [`ImportError::PointerOutOfRange`] for an
/// address the ROM does not hold, [`ImportError::Lz77`] for a stream that
/// will not decode, and [`ImportError::EntryShape`] for bytes that do not
/// fit the entry they shape into. [`ImportError::EmptyPack`] if every
/// domain produced nothing.
pub fn import_pack(rom_path: &Path) -> Result<ImportedPack, ImportError> {
    pack_from_rom(&Rom::load(rom_path)?)
}

/// Import an already-open ROM and hand back the finished pack.
///
/// [`import_pack`] for a caller that opened the ROM itself, and the entry
/// point for one that has to *keep* it open. A caller publishing the pack
/// over a destination has to know the destination is not the ROM, and a
/// path answers that question about whichever file it named at the moment
/// it was asked: another account able to redirect a component of the ROM's
/// path can let the check pass and the read land elsewhere. Handing the
/// same descriptor to both settles it — see [`Rom::read_from`]. `rom_path`
/// is carried for diagnostics only.
///
/// # Errors
///
/// As [`import_pack`]: [`ImportError::ReadFailed`] now names a handle that
/// could not be read rather than a path that could not be opened.
pub fn import_pack_from_file(
    rom: &std::fs::File,
    rom_path: &Path,
) -> Result<ImportedPack, ImportError> {
    pack_from_rom(&Rom::read_from(rom, rom_path)?)
}

/// Select `rom`'s profile and build its pack: the half of an import that
/// happens once the bytes are in hand, however they got there.
fn pack_from_rom(rom: &Rom) -> Result<ImportedPack, ImportError> {
    let profile = select_profile(rom)?;
    let (entry_count, bytes) = build_pack(rom, &profile.roots)?;
    Ok(ImportedPack::new(entry_count, bytes))
}

/// Import the ROM at `rom_path` and hand back the pack's bytes.
///
/// [`import_pack`] for a caller that wants only the bytes: the equivalence
/// gate compares a freshly imported pack against the checkout's without
/// touching disk.
///
/// # Errors
///
/// As [`import_pack`].
pub fn import_to_bytes(rom_path: &Path) -> Result<Vec<u8>, ImportError> {
    Ok(import_pack(rom_path)?.into_bytes())
}

/// Whether writing to `out_path` would land on the ROM at `rom_path`.
///
/// [`import`] guards its own write with this. It is public because the
/// binary's publish step needs the same answer about a *different* path:
/// `--import-rom` writes a temporary file and renames it into place, so
/// the rename is what would clobber the ROM, and the temporary file's own
/// name never matches it. On Unix that step asks the question of a
/// directory descriptor instead, which cannot be redirected mid-import;
/// this is the path-level answer it falls back to elsewhere.
///
/// A destination that already exists is compared by *file identity*, so a
/// hard link to the ROM under another name is still the ROM: the two names
/// share one inode, and writing through either truncates it. Otherwise the
/// comparison is on canonical paths, so a symlink, a `..`, or a relative
/// spelling of the ROM is still the ROM. The destination usually does not
/// exist yet and cannot be canonicalized directly, so it resolves as its
/// canonical parent plus its own file name. Answers `false` for anything it
/// cannot resolve — a ROM that does not exist has nothing to lose, and an
/// unresolvable destination is a write that fails on its own and reports
/// why.
#[must_use]
pub fn overwrites_rom(rom_path: &Path, out_path: &Path) -> bool {
    if is_same_file(rom_path, out_path) {
        return true;
    }
    let Ok(rom) = std::fs::canonicalize(rom_path) else {
        return false;
    };
    resolve_destination(out_path).is_some_and(|out| out == rom)
}

/// Whether `a` and `b` are two names for one file on disk.
///
/// Hard links give one inode several directory entries, and no comparison
/// of path *names* can see that: `canonicalize` resolves symlinks, but two
/// hard links to the same file canonicalize to their own distinct names.
/// A device and inode pair names the file itself.
///
/// Answers `false` when either path cannot be read — the caller falls back
/// to the path comparison, which fails open for the same reason.
#[cfg(unix)]
fn is_same_file(a: &Path, b: &Path) -> bool {
    use std::os::unix::fs::MetadataExt;

    // `metadata` follows symlinks, which is what the guard wants: the
    // question is which file the write lands on, not which name it took.
    let (Ok(a), Ok(b)) = (std::fs::metadata(a), std::fs::metadata(b)) else {
        return false;
    };
    a.dev() == b.dev() && a.ino() == b.ino()
}

/// Whether `a` and `b` are two names for one file on disk.
///
/// Always `false` off Unix: `std` exposes no stable file identity there.
/// Issue #1132's `windows-sys` approval covers only the handle-bound cleanup
/// delete ([`WindowsFileIdentity`]), not this alias check, which is
/// out of scope for that slice. The canonical-path comparison in
/// [`overwrites_rom`] still catches every alias that is not a hard link.
#[cfg(not(unix))]
fn is_same_file(_a: &Path, _b: &Path) -> bool {
    false
}

/// The canonical path `out_path` names, whether or not it exists yet.
fn resolve_destination(out_path: &Path) -> Option<PathBuf> {
    if let Ok(existing) = std::fs::canonicalize(out_path) {
        return Some(existing);
    }
    let name = out_path.file_name()?;
    // A bare file name has no parent, and a parent of `""` is not a
    // directory any OS accepts; both mean the current directory.
    let parent = match out_path.parent() {
        Some(parent) if !parent.as_os_str().is_empty() => parent,
        _ => Path::new("."),
    };
    Some(std::fs::canonicalize(parent).ok()?.join(name))
}

/// Write `bytes` to a file this call creates, refusing a path that is
/// already taken.
///
/// `fs::write` opens create-and-truncate, which *follows* a symlink
/// sitting at `out_path` and truncates whatever it points at. The
/// destination is always a fresh name the caller picked for a file that
/// does not exist yet, so anything already there is by definition not the
/// file this importer meant to write. In a directory another account can write to, a
/// player's own `$POKEEMERALD_PACK` choice, that is a planted link aimed
/// at a file of theirs, and the import would spend its write truncating
/// it.
///
/// Exclusive creation is the only open that cannot be redirected:
/// `O_CREAT | O_EXCL` refuses a symlink even a dangling one, and Windows'
/// `CREATE_NEW` refuses an existing name the same way. The attack becomes
/// a refused import naming the path, not a truncated file.
///
/// On Windows the handle also shares nothing (`share_mode(0)`, as
/// `create_new_exclusive` in `crates/engine/src/save/file/staging.rs`), so
/// no other opener can rename or delete `out_path`'s entry while it lives.
fn write_new(out_path: &Path, bytes: &[u8]) -> Result<(), WriteFailure> {
    write_new_with(out_path, |file| {
        use std::io::Write as _;
        file.write_all(bytes)
    })
}

/// [`write_new`] with the write injected, so the failure path is testable
/// without a full filesystem (`pokeemerald-rs`'s `import_to_with`
/// precedent).
///
/// A failed write hands the still-open handle to [`classify_partial_file`],
/// which reports what the destination holds; the caller sees the I/O
/// failure itself beside that reading.
fn write_new_with(
    out_path: &Path,
    write: impl FnOnce(&mut std::fs::File) -> std::io::Result<()>,
) -> Result<(), WriteFailure> {
    let mut options = std::fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt as _;

        options.share_mode(0);
    }
    let mut file = options.open(out_path).map_err(WriteFailure::gone)?;
    match write(&mut file) {
        Ok(()) => Ok(()),
        Err(error) => Err(classify_partial_file(out_path, file, error)),
    }
}

/// Whether `found`, the entry now at `path`, is the file `file` holds open:
/// Unix device and inode.
#[cfg(unix)]
fn is_the_created_file(file: &std::fs::File, found: &std::fs::Metadata) -> std::io::Result<bool> {
    use std::os::unix::fs::MetadataExt as _;
    let created = file.metadata()?;
    Ok((created.dev(), created.ino()) == (found.dev(), found.ino()))
}

/// Off Unix there is no inode: creation time, size, and last write from the
/// held handle, which an ancestor-junction retarget cannot pin, stand in.
/// [`confirmed_partial_file`] is what closes the window this leaves open on
/// Windows; off Windows the window stays open, since retention needs only
/// to tell a replacement from the original, not to remove it.
#[cfg(not(unix))]
fn is_the_created_file(file: &std::fs::File, found: &std::fs::Metadata) -> std::io::Result<bool> {
    use std::os::windows::fs::MetadataExt as _;

    let created = file.metadata()?;
    Ok((
        created.creation_time(),
        created.file_size(),
        created.last_write_time(),
    ) == (
        found.creation_time(),
        found.file_size(),
        found.last_write_time(),
    ))
}

/// Whether `path` still names the file `file` holds open, rather than a
/// symlink, directory, or other entry that took its name in the window
/// between the write failure and this check.
fn still_the_created_file(file: &std::fs::File, path: &Path) -> std::io::Result<bool> {
    let found = std::fs::symlink_metadata(path)?;
    Ok(found.file_type().is_file() && is_the_created_file(file, &found)?)
}

/// The identity `GetFileInformationByHandle` reads off an open handle:
/// volume serial number and file index, the one per-object identity Windows
/// exposes to a handle regardless of which path was used to open it (`std`'s
/// equivalent, `MetadataExt::volume_serial_number`/`file_index`, is still
/// gated on the unstable `windows_by_handle`, rust-lang/rust#63010).
///
/// Comparing this after opening `path` fresh, rather than the path metadata
/// [`is_the_created_file`] compares, is what lets
/// [`remove_through_verified_handle`] delete through the very handle it just
/// verified instead of re-resolving `path` a second time for the delete
/// itself (issue #1132; approval trail in the dependency ledger, `README.md`).
#[cfg(windows)]
#[derive(Clone, Copy, PartialEq, Eq)]
struct WindowsFileIdentity {
    volume_serial_number: u32,
    file_index: u64,
}

#[cfg(windows)]
impl WindowsFileIdentity {
    /// Reads the identity of the object `handle` refers to.
    fn of(handle: &std::fs::File) -> std::io::Result<Self> {
        use std::os::windows::io::AsRawHandle as _;
        use windows_sys::Win32::Storage::FileSystem::{
            GetFileInformationByHandle, BY_HANDLE_FILE_INFORMATION,
        };

        let mut info = BY_HANDLE_FILE_INFORMATION::default();
        // SAFETY: `handle` stays open for this call, and `info` is a correctly-sized out parameter the API fills in place.
        let ok = unsafe { GetFileInformationByHandle(handle.as_raw_handle(), &raw mut info) };
        if ok == 0 {
            return Err(std::io::Error::last_os_error());
        }
        Ok(Self {
            volume_serial_number: info.dwVolumeSerialNumber,
            file_index: (u64::from(info.nFileIndexHigh) << 32) | u64::from(info.nFileIndexLow),
        })
    }
}

/// Opens `path` for [`remove_through_verified_handle`]'s identity check and
/// delete: `DELETE | FILE_READ_ATTRIBUTES` access,
/// `FILE_FLAG_OPEN_REPARSE_POINT` so a reparse point planted at the final
/// component is not followed underneath the check, and
/// `FILE_FLAG_BACKUP_SEMANTICS` so a directory that took the name opens and
/// fails the identity check instead of failing the open as access denied.
///
/// The share mode admits every other opener. A deny-all open would fail as
/// a sharing violation whenever a scanner or indexer still held the freshly
/// written file, leaving it behind; sharing cannot redirect the check or the
/// delete, since both go through this handle.
#[cfg(windows)]
fn open_for_verified_delete(path: &Path) -> std::io::Result<std::fs::File> {
    use std::os::windows::fs::OpenOptionsExt as _;
    use windows_sys::Win32::Storage::FileSystem::{
        DELETE, FILE_FLAG_BACKUP_SEMANTICS, FILE_FLAG_OPEN_REPARSE_POINT, FILE_READ_ATTRIBUTES,
        FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE,
    };

    std::fs::OpenOptions::new()
        .access_mode(DELETE | FILE_READ_ATTRIBUTES)
        .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE)
        .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT | FILE_FLAG_BACKUP_SEMANTICS)
        .open(path)
}

/// What [`remove_through_verified_handle`] did about `path`.
#[cfg(windows)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum VerifiedRemoval {
    /// `path` no longer reached the verified object, so nothing was touched.
    NotOurs,
    /// The object was deleted with POSIX semantics: its name left the
    /// directory when the verifying handle closed, even if another process
    /// still holds the object open.
    Unlinked,
    /// The volume refused POSIX semantics, so the object was only marked
    /// delete-on-close: its name stays in the directory, refusing a
    /// same-name create, until every other handle to it closes.
    Pending,
}

/// Deletes the object `handle` refers to through `handle` itself rather
/// than a second lookup of its path.
///
/// POSIX semantics (`FileDispositionInfoEx`) is tried first, so the name is
/// gone once `handle` closes whatever other opener remains. A volume or
/// Windows release without it answers `ERROR_NOT_SUPPORTED`,
/// `ERROR_INVALID_PARAMETER`, or `ERROR_INVALID_FUNCTION`, and falls back to
/// the plain `FileDispositionInfo` delete-on-close, reported as
/// [`VerifiedRemoval::Pending`] because another handle can hold the name.
#[cfg(windows)]
fn delete_through_handle(handle: &std::fs::File) -> std::io::Result<VerifiedRemoval> {
    use windows_sys::Win32::Foundation::{
        ERROR_INVALID_FUNCTION, ERROR_INVALID_PARAMETER, ERROR_NOT_SUPPORTED,
    };
    use windows_sys::Win32::Storage::FileSystem::{
        FileDispositionInfo, FileDispositionInfoEx, FILE_DISPOSITION_FLAG_DELETE,
        FILE_DISPOSITION_FLAG_POSIX_SEMANTICS, FILE_DISPOSITION_INFO, FILE_DISPOSITION_INFO_EX,
    };

    let posix = FILE_DISPOSITION_INFO_EX {
        Flags: FILE_DISPOSITION_FLAG_DELETE | FILE_DISPOSITION_FLAG_POSIX_SEMANTICS,
    };
    // SAFETY: `FileDispositionInfoEx` takes a `FILE_DISPOSITION_INFO_EX`, which `posix` is.
    match unsafe { set_file_information(handle, FileDispositionInfoEx, &posix) } {
        Ok(()) => return Ok(VerifiedRemoval::Unlinked),
        Err(refused)
            if refused
                .raw_os_error()
                .and_then(|code| u32::try_from(code).ok())
                .is_some_and(|code| {
                    matches!(
                        code,
                        ERROR_NOT_SUPPORTED | ERROR_INVALID_PARAMETER | ERROR_INVALID_FUNCTION
                    )
                }) => {}
        Err(failed) => return Err(failed),
    }
    let legacy = FILE_DISPOSITION_INFO { DeleteFile: true };
    // SAFETY: `FileDispositionInfo` takes a `FILE_DISPOSITION_INFO`, which `legacy` is.
    unsafe { set_file_information(handle, FileDispositionInfo, &legacy) }?;
    Ok(VerifiedRemoval::Pending)
}

/// `SetFileInformationByHandle` on `handle` with `info` as the buffer.
///
/// # Safety
///
/// `T` must be the structure `class` documents as its buffer.
#[cfg(windows)]
unsafe fn set_file_information<T>(
    handle: &std::fs::File,
    class: windows_sys::Win32::Storage::FileSystem::FILE_INFO_BY_HANDLE_CLASS,
    info: &T,
) -> std::io::Result<()> {
    use std::os::windows::io::AsRawHandle as _;
    use windows_sys::Win32::Storage::FileSystem::SetFileInformationByHandle;

    let size = u32::try_from(std::mem::size_of::<T>())
        .expect("a file-information structure is far smaller than u32::MAX");
    // SAFETY: `handle` stays open for the call, the caller guarantees `T` matches `class`, and `size` is `T`'s exact size.
    let ok = unsafe {
        SetFileInformationByHandle(
            handle.as_raw_handle(),
            class,
            std::ptr::from_ref(info).cast(),
            size,
        )
    };
    if ok == 0 {
        Err(std::io::Error::last_os_error())
    } else {
        Ok(())
    }
}

/// Removes the file `identity` names if `path` still reaches it, deleting
/// through the same handle the identity check opens so no re-lookup of
/// `path` occurs between the check and the delete. A path that now reaches a
/// different object -- or nothing at all -- is left alone
/// ([`VerifiedRemoval::NotOurs`]).
#[cfg(windows)]
fn remove_through_verified_handle(
    path: &Path,
    identity: WindowsFileIdentity,
) -> std::io::Result<VerifiedRemoval> {
    remove_through_verified_handle_with(path, identity, |_handle| {})
}

/// [`remove_through_verified_handle`] with a hook run between the identity
/// check and the delete, so a test can land a retarget in exactly that
/// window without a real race: a test's only other way to reach it would be
/// two threads racing the OS, which no cheap seam makes deterministic.
#[cfg(windows)]
fn remove_through_verified_handle_with(
    path: &Path,
    identity: WindowsFileIdentity,
    before_delete: impl FnOnce(&std::fs::File),
) -> std::io::Result<VerifiedRemoval> {
    let handle = match open_for_verified_delete(path) {
        Ok(handle) => handle,
        Err(missing) if missing.kind() == std::io::ErrorKind::NotFound => {
            return Ok(VerifiedRemoval::NotOurs)
        }
        Err(open_err) => return Err(open_err),
    };
    if WindowsFileIdentity::of(&handle)? != identity {
        return Ok(VerifiedRemoval::NotOurs);
    }
    before_delete(&handle);
    delete_through_handle(&handle)
}

/// A failed write, with what cleanup then saw at the destination.
///
/// The write layer never learns the path as the caller spelled it --
/// [`ImportError::WriteFailed`] is what renders that -- so this carries the
/// failure and the finding and nothing else. [`WriteFailure::at`] is the
/// one way it becomes a caller's error.
#[derive(Debug)]
struct WriteFailure {
    /// What was at the destination when cleanup looked.
    partial: PartialFile,
    /// The I/O failure itself, untouched.
    source: std::io::Error,
}

impl WriteFailure {
    /// A failure that left nothing of the importer's behind: the open
    /// itself was refused, so there is no partial file to have an opinion
    /// about.
    fn gone(source: std::io::Error) -> Self {
        Self {
            partial: PartialFile::Gone,
            source,
        }
    }

    /// The failure as the caller sees it, against the destination it was
    /// aimed at.
    ///
    /// `source` crosses untouched, which is the whole point of the split:
    /// it is the I/O failure [`ImportError::WriteFailed`] documents, and a
    /// caller tells a quota failure from a device one by reading
    /// `raw_os_error` off it. Anything cleanup observed is already in
    /// `partial`, so nothing has to wrap the error to say it.
    fn at(self, path: &Path) -> ImportError {
        ImportError::WriteFailed {
            path: path.to_path_buf(),
            partial: self.partial,
            source: self.source,
        }
    }
}

/// Leaves the partial file `write_new_with` created at `path` in place
/// after `original` and classifies what is there for the caller; a
/// replacement is left alone. A retry against `path` fails closed until the
/// caller clears it. An identity check that cannot read `path` is
/// [`PartialFile::Unreadable`] rather than a failure of its own; `NotFound`
/// means nothing was left to look for. What a confirmed file becomes is
/// [`confirmed_partial_file`]'s call, which differs by platform.
fn classify_partial_file(
    path: &Path,
    file: std::fs::File,
    original: std::io::Error,
) -> WriteFailure {
    let partial = match still_the_created_file(&file, path) {
        Ok(true) => confirmed_partial_file(path, file),
        Ok(false) => PartialFile::Gone,
        Err(missing) if missing.kind() == std::io::ErrorKind::NotFound => PartialFile::Gone,
        Err(unreadable) => PartialFile::Unreadable(unreadable),
    };
    WriteFailure {
        partial,
        source: original,
    }
}

/// What [`classify_partial_file`] reports once identity confirms `path`
/// still names the file `file` holds open, off Windows: retained, since
/// stable `std` has no removal bound to the checked identity rather than to
/// a name there.
#[cfg(not(windows))]
fn confirmed_partial_file(_path: &Path, file: std::fs::File) -> PartialFile {
    drop(file);
    PartialFile::MayRemain
}

/// [`confirmed_partial_file`] on Windows: reads `file`'s own identity, gives
/// up the handle (Windows refuses to remove or reopen-for-delete a file
/// this process still holds), then deletes through
/// [`remove_through_verified_handle`] rather than retaining. A failure
/// reading the identity or performing the delete is
/// [`PartialFile::RemovalFailed`] rather than discarded. A delete the volume
/// could only leave pending ([`VerifiedRemoval::Pending`]) is
/// [`PartialFile::MayRemain`]: another process's handle can keep the name
/// refusing a same-name retry, so it is not reported as gone.
#[cfg(windows)]
fn confirmed_partial_file(path: &Path, file: std::fs::File) -> PartialFile {
    let identity = match WindowsFileIdentity::of(&file) {
        Ok(identity) => identity,
        Err(unreadable) => {
            drop(file);
            return PartialFile::RemovalFailed(unreadable);
        }
    };
    drop(file);
    match remove_through_verified_handle(path, identity) {
        Ok(VerifiedRemoval::NotOurs | VerifiedRemoval::Unlinked) => PartialFile::Gone,
        Ok(VerifiedRemoval::Pending) => PartialFile::MayRemain,
        Err(removal_failed) => PartialFile::RemovalFailed(removal_failed),
    }
}

/// Run every domain reader over `rom` and serialize the pack.
///
/// Returns the entry count alongside the bytes, so a report does not have
/// to re-parse what it just wrote.
fn build_pack(rom: &Rom, roots: &Roots) -> Result<(usize, Vec<u8>), ImportError> {
    let mut writer = pack_format::PackWriter::new();
    for domain in domains::DOMAINS {
        domain(rom, roots, &mut writer)?;
    }
    let entry_count = writer.len();
    if entry_count == 0 {
        return Err(ImportError::EmptyPack);
    }
    Ok((entry_count, writer.finish()?))
}

#[cfg(test)]
mod tests {
    use super::{
        build_pack, import, import_to_bytes, overwrites_rom, write_new, write_new_with,
        ImportError, ImportReport, PartialFile, Roots, WriteFailure,
    };
    use crate::fixture::{shared_emerald_rom, RomFixture};
    use std::path::{Path, PathBuf};

    #[cfg(windows)]
    use super::{
        remove_through_verified_handle, remove_through_verified_handle_with, VerifiedRemoval,
        WindowsFileIdentity,
    };

    #[test]
    fn import_fails_closed_on_a_missing_rom() {
        let out = Path::new("/nonexistent/rom-import/out.pack");
        let err = import(Path::new("/nonexistent/rom-import/rom.gba"), out).unwrap_err();
        assert!(matches!(err, ImportError::ReadFailed { .. }));
        assert!(matches!(
            import_to_bytes(Path::new("/nonexistent/rom-import/rom.gba")).unwrap_err(),
            ImportError::ReadFailed { .. }
        ));
    }

    #[test]
    fn a_rejected_rom_never_reaches_the_write() {
        // The importer must reject before it can reach a write, so a path it
        // could never create is a safe target.
        let out = Path::new("/nonexistent/rom-import/out.pack");
        assert!(import(Path::new("/dev/null"), out).is_err());
        assert!(!out.exists());
    }

    #[test]
    fn a_profile_with_no_roots_fails_closed() {
        // An empty pack would look like a successful import to every
        // downstream check, so it is an error rather than a 16-byte file.
        let err = build_pack(shared_emerald_rom(), &Roots::NONE).unwrap_err();
        assert!(matches!(err, ImportError::EmptyPack));
    }

    /// A fresh directory under the OS temporary directory, removed on drop.
    struct TempDir {
        path: PathBuf,
    }

    impl TempDir {
        fn new(label: &str) -> Self {
            use std::sync::atomic::{AtomicU32, Ordering};
            static COUNTER: AtomicU32 = AtomicU32::new(0);
            let unique = COUNTER.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "rom-import-{label}-{}-{unique}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&path);
            std::fs::create_dir_all(&path).expect("a temporary directory");
            Self { path }
        }

        fn join(&self, name: &str) -> PathBuf {
            self.path.join(name)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }

    /// Write a header-valid synthetic ROM image and return its path.
    ///
    /// It gets past every structural check and is rejected on identity
    /// alone, so a test can reach the code that runs *after* `Rom::load`
    /// without a real cartridge.
    fn write_fixture_rom(dir: &TempDir, name: &str) -> PathBuf {
        let path = dir.join(name);
        std::fs::write(&path, RomFixture::new().emerald_header().finish())
            .expect("the fixture writes");
        path
    }

    #[test]
    fn importing_onto_the_source_rom_is_refused_with_the_rom_intact() {
        // `Rom::load` reads the image whole before anything is written, so
        // this write would succeed and leave the player holding a pack
        // where their cartridge image used to be.
        let dir = TempDir::new("same-file");
        let rom_path = write_fixture_rom(&dir, "emerald.gba");
        let before = std::fs::read(&rom_path).expect("the fixture reads back");

        let err = import(&rom_path, &rom_path).unwrap_err();
        assert!(matches!(err, ImportError::SameFile { .. }), "{err:?}");
        assert_eq!(
            std::fs::read(&rom_path).expect("the ROM survives"),
            before,
            "the ROM must be byte-identical after a refused import"
        );
    }

    #[test]
    fn a_relative_or_symlinked_spelling_of_the_rom_is_still_the_rom() {
        // Canonical paths, not string equality: `./emerald.gba` and a
        // detour through `..` name the same file the importer just read.
        let dir = TempDir::new("aliases");
        let rom_path = write_fixture_rom(&dir, "emerald.gba");
        let detour = dir.join("nested").join("..").join("emerald.gba");
        std::fs::create_dir_all(dir.join("nested")).expect("the nested directory");
        assert!(overwrites_rom(&rom_path, &detour));

        // A file beside it that does not exist yet is a legal destination,
        // and so is one whose directory does not exist.
        assert!(!overwrites_rom(&rom_path, &dir.join("pokeemerald.pack")));
        assert!(!overwrites_rom(
            &rom_path,
            &dir.join("nowhere").join("pokeemerald.pack")
        ));
    }

    #[test]
    #[cfg(unix)]
    fn a_hard_link_to_the_rom_is_still_the_rom() {
        // A hard link is the one alias no comparison of path names can see:
        // both entries canonicalize to themselves while sharing an inode, so
        // `fs::write` to the link truncates the ROM the importer just read.
        let dir = TempDir::new("hard-link");
        let rom_path = write_fixture_rom(&dir, "emerald.gba");
        let before = std::fs::read(&rom_path).expect("the fixture reads back");
        let link = dir.join("pokeemerald.pack");
        std::fs::hard_link(&rom_path, &link).expect("the hard link");
        assert_ne!(
            std::fs::canonicalize(&rom_path).expect("the ROM canonicalizes"),
            std::fs::canonicalize(&link).expect("the link canonicalizes"),
            "the test is pointless unless the two names really do differ"
        );

        assert!(overwrites_rom(&rom_path, &link));
        let err = import(&rom_path, &link).unwrap_err();
        assert!(matches!(err, ImportError::SameFile { .. }), "{err:?}");
        assert_eq!(
            std::fs::read(&rom_path).expect("the ROM survives"),
            before,
            "the ROM must be byte-identical after a refused import"
        );
    }

    #[test]
    fn a_missing_rom_never_reports_a_collision() {
        // Nothing is at risk, so the missing ROM stays the diagnosis.
        let missing = Path::new("/nonexistent/rom-import/rom.gba");
        assert!(!overwrites_rom(missing, missing));
        assert!(matches!(
            import(missing, missing).unwrap_err(),
            ImportError::ReadFailed { .. }
        ));
    }

    #[test]
    fn a_fresh_destination_is_written_whole() {
        let dir = TempDir::new("write-new");
        let out = dir.join("pokeemerald.pack");
        write_new(&out, b"pack bytes").expect("a name nothing holds");
        assert_eq!(
            std::fs::read(&out).expect("the pack reads back"),
            b"pack bytes"
        );
    }

    #[test]
    fn a_destination_that_already_exists_is_refused_intact() {
        // The importer only ever writes a name its caller reserved for a
        // file that does not exist. Anything already there belongs to
        // someone else, so it is refused rather than truncated.
        let dir = TempDir::new("write-taken");
        let out = dir.join("pokeemerald.pack");
        std::fs::write(&out, b"not the importer's").expect("the existing file writes");

        let err = write_new(&out, b"pack bytes").unwrap_err();
        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::AlreadyExists,
            "{:?}",
            err.source
        );
        assert_eq!(
            std::fs::read(&out).expect("the existing file survives"),
            b"not the importer's"
        );
    }

    #[test]
    #[cfg(not(windows))]
    fn a_failed_write_retains_its_partial_file_until_the_caller_removes_it() {
        // A write that dies part-way -- a full disk -- leaves a prefix of
        // the pack behind, and cleanup retains it rather than removing it.
        // The non-Windows contract; `a_failed_write_is_removed_through_its_verified_handle_on_windows`
        // below is the Windows upgrade (issue #1132).
        let dir = TempDir::new("write-fails");
        let out = dir.join("pokeemerald.pack");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            Err(std::io::Error::new(
                std::io::ErrorKind::StorageFull,
                "no space left on device",
            ))
        })
        .unwrap_err();

        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::StorageFull,
            "{err:?}"
        );
        assert!(
            matches!(err.partial, PartialFile::MayRemain),
            "{:?}",
            err.partial
        );
        let text = err.at(&out).to_string();
        assert!(
            text.contains("no space left on device"),
            "the write's own error must survive: {text}"
        );
        assert!(
            text.contains("pokeemerald.pack"),
            "the retained file's path must be named: {text}"
        );
        assert_eq!(
            std::fs::read(&out).expect("the partial file is retained"),
            b"half a ",
            "cleanup must not remove the call's own partial file"
        );

        // The name is not free: a retry hits the retained debris.
        let retry = write_new(&out, b"pack bytes").unwrap_err();
        assert_eq!(
            retry.source.kind(),
            std::io::ErrorKind::AlreadyExists,
            "{:?}",
            retry.source
        );
        assert_eq!(
            std::fs::read(&out).expect("the partial file still survives the refused retry"),
            b"half a "
        );

        // Only once the caller clears the name themselves does a retry land.
        std::fs::remove_file(&out).expect("the caller's own cleanup");
        write_new(&out, b"pack bytes").expect("the retry takes the name once it is cleared");
        assert_eq!(
            std::fs::read(&out).expect("the pack reads back"),
            b"pack bytes"
        );
    }

    #[test]
    #[cfg(windows)]
    fn a_failed_write_is_removed_through_its_verified_handle_on_windows() {
        // The Windows upgrade over the retention contract above (issue
        // #1132): the confirmed partial file is deleted through the same
        // handle its identity was checked against, so nothing is left for
        // the caller to clear and a retry lands at the same name directly.
        let dir = TempDir::new("write-fails-windows");
        let out = dir.join("pokeemerald.pack");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            Err(std::io::Error::new(
                std::io::ErrorKind::StorageFull,
                "no space left on device",
            ))
        })
        .unwrap_err();

        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::StorageFull,
            "{err:?}"
        );
        assert!(
            matches!(err.partial, PartialFile::Gone),
            "{:?}",
            err.partial
        );
        assert!(
            !out.exists(),
            "the verified-handle delete must remove the call's own partial file"
        );

        // The name is free: a retry lands directly, with no debris to clear.
        write_new(&out, b"pack bytes").expect("the retry takes the name with nothing left over");
        assert_eq!(
            std::fs::read(&out).expect("the pack reads back"),
            b"pack bytes"
        );
    }

    #[test]
    #[cfg(unix)]
    fn cleanup_leaves_a_directory_that_replaced_the_partial_file_alone() {
        // The write closure swaps the partial file for a non-empty
        // directory before returning its error. A directory is not a
        // regular file, so `classify_partial_file`'s identity check classifies it as
        // a replacement and never attempts to remove it, mirroring
        // `StagedSave::remove_after`'s `Ok(false) => return source`
        // (`crates/engine/src/save/file/staging.rs`).
        let dir = TempDir::new("write-cleanup-directory-swap");
        let out = dir.join("pokeemerald.pack");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            drop(std::fs::remove_file(&out));
            std::fs::create_dir(&out).expect("the directory takes the freed name");
            std::fs::write(out.join("occupant"), b"occupant").expect("the occupant writes");
            Err(std::io::Error::new(
                std::io::ErrorKind::StorageFull,
                "no space left on device",
            ))
        })
        .unwrap_err();

        // Cleanup never touched the directory, so the write's own error
        // comes back unmodified and nothing of the importer's is reported
        // left behind.
        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::StorageFull,
            "{err:?}"
        );
        assert_eq!(err.source.to_string(), "no space left on device");
        assert!(
            matches!(err.partial, PartialFile::Gone),
            "{:?}",
            err.partial
        );
        assert!(
            out.is_dir(),
            "cleanup must leave a directory that replaced the partial file alone"
        );
        assert_eq!(
            std::fs::read(out.join("occupant")).expect("the occupant survives"),
            b"occupant"
        );
    }

    #[test]
    #[cfg(unix)]
    fn cleanup_leaves_a_file_that_replaced_the_partial_one_alone() {
        // A peer swaps its own file in at `out` during the write; cleanup
        // must leave it (`classify_partial_file`'s contract).
        let dir = TempDir::new("write-cleanup-file-swap");
        let out = dir.join("pokeemerald.pack");
        let renamed_aside = dir.join("pokeemerald.pack.moved");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            std::fs::rename(&out, &renamed_aside).expect("the peer renames the partial file aside");
            std::fs::write(&out, b"the replacement").expect("the peer's own file takes the name");
            Err(std::io::Error::new(
                std::io::ErrorKind::StorageFull,
                "no space left on device",
            ))
        })
        .unwrap_err();

        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::StorageFull,
            "{err:?}"
        );
        assert_eq!(err.source.to_string(), "no space left on device");
        assert!(
            matches!(err.partial, PartialFile::Gone),
            "{:?}",
            err.partial
        );
        assert_eq!(
            std::fs::read(&out).expect("the replacement survives"),
            b"the replacement",
            "cleanup must never remove an entry that replaced this call's partial file"
        );
        assert_eq!(
            std::fs::read(&renamed_aside).expect("the renamed-aside partial file survives"),
            b"half a ",
            "cleanup must not disturb the partial file once it is no longer at `out`"
        );
    }

    #[test]
    #[cfg(unix)]
    fn cleanup_leaves_a_file_reached_through_a_retargeted_ancestor_alone() {
        // The peer never touches the created file or its name: it retargets
        // an *ancestor* link, so the same `out` pathname comes to resolve to
        // an unrelated regular file in another directory. Only an identity
        // read of the entry found there can tell cleanup that the name no
        // longer means the file it created -- a hold on the created file
        // says nothing about which directory the path now walks through.
        let dir = TempDir::new("write-cleanup-ancestor-swap");
        let target = dir.join("a");
        let elsewhere = dir.join("b");
        std::fs::create_dir(&target).expect("the link's first target");
        std::fs::create_dir(&elsewhere).expect("the link's second target");
        let victim = elsewhere.join("pokeemerald.pack");
        std::fs::write(&victim, b"someone else's file").expect("the unrelated file exists");

        let link = dir.join("link");
        std::os::unix::fs::symlink(&target, &link).expect("the ancestor link");
        let out = link.join("pokeemerald.pack");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            std::fs::remove_file(&link).expect("the peer drops the ancestor link");
            std::os::unix::fs::symlink(&elsewhere, &link)
                .expect("the peer retargets the ancestor link");
            Err(std::io::Error::new(
                std::io::ErrorKind::StorageFull,
                "no space left on device",
            ))
        })
        .unwrap_err();

        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::StorageFull,
            "{err:?}"
        );
        assert_eq!(
            std::fs::read(&victim).expect("the unrelated file survives"),
            b"someone else's file",
            "cleanup must never remove a file the path only reaches through a retargeted ancestor"
        );
    }

    /// Whether `err` is Windows reporting that an open handle's share mode
    /// admits no one else. `std` categorises `ERROR_SHARING_VIOLATION` on
    /// some Windows versions and not others, so both spellings count
    /// (`crates/engine/src/save/file/staging/tests.rs` says the same).
    #[cfg(windows)]
    fn is_a_sharing_violation(err: &std::io::Error) -> bool {
        const ERROR_SHARING_VIOLATION: i32 = 32;

        err.kind() == std::io::ErrorKind::PermissionDenied
            || err.raw_os_error() == Some(ERROR_SHARING_VIOLATION)
    }

    #[test]
    #[cfg(windows)]
    fn the_output_cannot_be_replaced_or_removed_while_its_handle_lives() {
        // The Windows counterpart to the two swap regressions above: there a
        // peer plants the swap and the identity check catches it, while here
        // `write_new`'s deny-all share mode makes the swap unattemptable in
        // the first place, before `confirmed_partial_file`'s handle-bound
        // delete ever runs. Drop that share mode and each of these three steps
        // succeeds again, restoring the deletion of a swapped-in regular
        // file. Mirrors
        // `a_staged_image_cannot_be_opened_or_removed_while_its_hold_lives`
        // in `crates/engine/src/save/file/staging/tests.rs`.
        let dir = TempDir::new("write-exclusive-hold");
        let out = dir.join("pokeemerald.pack");
        let aside = dir.join("pokeemerald.pack.moved");
        let replacement = dir.join("replacement.pack");
        std::fs::write(&replacement, b"the replacement").expect("the peer's own file exists");

        write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;

            let renamed = std::fs::rename(&out, &aside)
                .expect_err("a held output must refuse being renamed aside");
            assert!(
                is_a_sharing_violation(&renamed),
                "renaming a held output aside must fail as a sharing violation: {renamed:?}"
            );

            let replaced = std::fs::rename(&replacement, &out)
                .expect_err("a held output must refuse being replaced");
            assert!(
                is_a_sharing_violation(&replaced),
                "replacing a held output must fail as a sharing violation: {replaced:?}"
            );

            let removed =
                std::fs::remove_file(&out).expect_err("a held output must refuse deletion");
            assert!(
                is_a_sharing_violation(&removed),
                "deleting a held output must fail as a sharing violation: {removed:?}"
            );

            Ok(())
        })
        .expect("a write whose output nobody else could touch must succeed");

        assert_eq!(
            std::fs::read(&out).expect("the output survives the refused attempts"),
            b"half a "
        );
        assert!(
            !aside.exists(),
            "a refused rename must not leave the output under the peer's name"
        );
        assert_eq!(
            std::fs::read(&replacement).expect("the peer's own file is untouched"),
            b"the replacement"
        );
    }

    /// Points the directory junction at `link` at `target`, replacing
    /// whatever it named before. Unlike a directory symlink this needs no
    /// privilege, so the Windows ancestor-retarget regressions below never
    /// have to skip.
    #[cfg(windows)]
    fn junction(link: &Path, target: &Path) {
        let status = std::process::Command::new("cmd")
            .args(["/C", "mklink", "/J"])
            .arg(link)
            .arg(target)
            .stdout(std::process::Stdio::null())
            .status()
            .expect("cmd runs mklink");
        assert!(
            status.success(),
            "mklink /J {} {}: {status}",
            link.display(),
            target.display()
        );
    }

    #[test]
    #[cfg(windows)]
    fn cleanup_leaves_a_file_reached_through_a_retargeted_ancestor_alone() {
        // The Windows counterpart to the identically named Unix test above:
        // a directory junction stands in for the ancestor link a peer
        // retargets, closing the gap `write_new`'s deny-all `share_mode(0)`
        // leaves open, since that hold only ever covers `out`'s own entry
        // and never the directories the path walks through to reach it.
        let dir = TempDir::new("write-cleanup-ancestor-swap");
        let target = dir.join("a");
        let elsewhere = dir.join("b");
        std::fs::create_dir(&target).expect("the link's first target");
        std::fs::create_dir(&elsewhere).expect("the link's second target");
        let victim = elsewhere.join("pokeemerald.pack");
        std::fs::write(&victim, b"someone else's file").expect("the unrelated file exists");

        let link = dir.join("link");
        junction(&link, &target);
        let out = link.join("pokeemerald.pack");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            std::fs::remove_dir(&link).expect("the peer drops the ancestor junction");
            junction(&link, &elsewhere);
            Err(std::io::Error::new(
                std::io::ErrorKind::StorageFull,
                "no space left on device",
            ))
        })
        .unwrap_err();

        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::StorageFull,
            "{err:?}"
        );
        assert_eq!(
            std::fs::read(&victim).expect("the unrelated file survives"),
            b"someone else's file",
            "cleanup must never remove a file the path only reaches through a retargeted ancestor"
        );
    }

    #[test]
    #[cfg(windows)]
    fn deletion_survives_an_ancestor_retargeted_between_the_check_and_the_delete() {
        // The two ancestor-retarget tests above complete their swap before
        // cleanup starts, so an implementation that re-resolves `path` for
        // both the check and the delete would already pass them. This
        // exercises the narrower window: `before_delete` runs the retarget
        // after `remove_through_verified_handle_with` has already opened
        // and identity-checked its handle, and only then may it delete. A
        // handle-bound delete must still remove exactly the object it
        // opened; it must never reach whatever the retargeted path now
        // resolves to.
        use std::io::Write as _;

        let dir = TempDir::new("write-cleanup-race-window");
        let target = dir.join("a");
        let elsewhere = dir.join("b");
        std::fs::create_dir(&target).expect("the link's first target");
        std::fs::create_dir(&elsewhere).expect("the link's second target");
        let victim = elsewhere.join("pokeemerald.pack");
        std::fs::write(&victim, b"someone else's file").expect("the unrelated file exists");

        let link = dir.join("link");
        junction(&link, &target);
        let out = link.join("pokeemerald.pack");
        let created = target.join("pokeemerald.pack");

        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&out)
            .expect("the exclusive create succeeds");
        file.write_all(b"half a ")
            .expect("the partial write succeeds");
        let identity = WindowsFileIdentity::of(&file).expect("identity reads back off the handle");
        drop(file);

        remove_through_verified_handle_with(&out, identity, |_handle| {
            std::fs::remove_dir(&link).expect("the peer drops the ancestor junction");
            junction(&link, &elsewhere);
        })
        .expect("a retarget after the check must not stop the handle-bound delete");

        assert!(
            !created.exists(),
            "the delete must remove the object identity was checked against, through its handle"
        );
        assert_eq!(
            std::fs::read(&victim).expect("the unrelated file survives"),
            b"someone else's file",
            "a retarget landing after the check must never redirect the delete onto it"
        );
    }

    #[test]
    #[cfg(windows)]
    fn cleanup_leaves_a_directory_that_took_the_name_alone() {
        // A directory opens only with `FILE_FLAG_BACKUP_SEMANTICS`; without
        // it the verifying open fails as access denied and a partial file
        // already gone would be reported as `RemovalFailed`.
        let dir = TempDir::new("write-cleanup-directory-swap");
        let out = dir.join("pokeemerald.pack");
        let file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&out)
            .expect("the exclusive create succeeds");
        let identity = WindowsFileIdentity::of(&file).expect("identity reads back off the handle");
        drop(file);
        std::fs::remove_file(&out).expect("the peer removes the partial file");
        std::fs::create_dir(&out).expect("the peer plants a directory at its name");

        let removal = remove_through_verified_handle(&out, identity)
            .expect("a directory at the name is identified, not an open failure");

        assert_eq!(removal, VerifiedRemoval::NotOurs);
        assert!(out.is_dir(), "the peer's directory must survive cleanup");
    }

    #[test]
    #[cfg(windows)]
    fn cleanup_deletes_a_partial_file_another_process_still_reads() {
        // A scanner or indexer opening the freshly written file must not
        // turn cleanup into a sharing violation, and a POSIX delete must
        // free the name while that reader still holds its handle.
        let dir = TempDir::new("write-cleanup-shared-reader");
        let out = dir.join("pokeemerald.pack");
        let file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&out)
            .expect("the exclusive create succeeds");
        let identity = WindowsFileIdentity::of(&file).expect("identity reads back off the handle");
        drop(file);
        let reader = std::fs::File::open(&out).expect("a sharing reader opens the partial file");

        let removal = remove_through_verified_handle(&out, identity)
            .expect("a sharing reader must not refuse the verified delete");

        match removal {
            VerifiedRemoval::Unlinked => {
                std::fs::OpenOptions::new()
                    .write(true)
                    .create_new(true)
                    .open(&out)
                    .expect("an unlinked name is free for a same-name retry at once");
            }
            VerifiedRemoval::Pending => {}
            VerifiedRemoval::NotOurs => panic!("the verified file was still at its name"),
        }
        drop(reader);
    }

    #[test]
    fn a_retained_partial_file_keeps_its_message_on_one_line() {
        // A newline or ESC byte in `out_path` must not survive into the
        // message the retained-file finding produces (see
        // `error::path_bearing_messages_are_escaped_and_stay_one_line`).
        //
        // Driven through `WriteFailure::at` rather than through a real
        // failed write: a name holding those bytes cannot exist on Windows,
        // where the exclusive create is refused with `InvalidFilename`
        // before any write can fail, so a filesystem-driven spelling of
        // this test can only ever run on Unix. The rendering is what is
        // under test, and it renders the path the caller handed in.
        let out = Path::new("packs/one\ntwo\u{1b}[2Kthree.pack");

        let err = WriteFailure {
            partial: PartialFile::MayRemain,
            source: std::io::Error::new(std::io::ErrorKind::StorageFull, "no space left on device"),
        }
        .at(out);

        let text = err.to_string();
        assert!(text.contains("no space left on device"), "{text:?}");
        assert!(text.contains("a partial file may remain there"), "{text:?}");
        assert!(!text.contains('\n'), "{text:?}");
        assert!(!text.contains('\u{1b}'), "{text:?}");
        assert!(
            text.contains(r"one\ntwo\u{1b}[2Kthree.pack"),
            "escaped name missing from {text:?}"
        );
    }

    #[test]
    fn a_failed_identity_check_keeps_its_message_on_one_line() {
        // The other cleanup finding appends to the same line and owes the
        // same promise. It was covered off Unix only, through the injected
        // removal that no longer exists; this restores the coverage on
        // every platform.
        let out = Path::new("packs/one\ntwo\u{1b}[2Kthree.pack");

        let err = WriteFailure {
            partial: PartialFile::Unreadable(std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                "permission denied",
            )),
            source: std::io::Error::new(std::io::ErrorKind::StorageFull, "no space left on device"),
        }
        .at(out);

        let text = err.to_string();
        assert!(text.contains("permission denied"), "{text:?}");
        assert!(!text.contains('\n'), "{text:?}");
        assert!(!text.contains('\u{1b}'), "{text:?}");
        assert!(
            text.contains(r"one\ntwo\u{1b}[2Kthree.pack"),
            "escaped name missing from {text:?}"
        );
    }

    #[test]
    fn a_failed_removal_keeps_its_message_on_one_line_and_its_own_reason() {
        // Windows's verified-handle delete can fail after confirming the
        // file is there; that reason must survive on the caller-facing
        // line rather than being discarded (issue #1132).
        let out = Path::new("packs/one\ntwo\u{1b}[2Kthree.pack");

        let err = WriteFailure {
            partial: PartialFile::RemovalFailed(std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                "access is denied",
            )),
            source: std::io::Error::new(std::io::ErrorKind::StorageFull, "no space left on device"),
        }
        .at(out);

        let text = err.to_string();
        assert!(text.contains("no space left on device"), "{text:?}");
        assert!(text.contains("access is denied"), "{text:?}");
        assert!(!text.contains('\n'), "{text:?}");
        assert!(!text.contains('\u{1b}'), "{text:?}");
        assert!(
            text.contains(r"one\ntwo\u{1b}[2Kthree.pack"),
            "escaped name missing from {text:?}"
        );
    }

    #[test]
    #[cfg(not(windows))]
    fn a_retained_partial_file_still_hands_back_the_write_error_itself() {
        // The boundary a caller actually sees, on the non-Windows contract
        // where the partial file is retained rather than removed.
        // `ImportError::WriteFailed` documents `source` as the underlying
        // I/O failure, and
        // `raw_os_error` is how a caller tells a quota failure from a
        // device one; a cleanup finding is something to report alongside
        // it, never something to wrap it in. `WriteFailure::at` is the
        // same conversion `import` performs.
        const OS_ERROR: i32 = 28;
        let dir = TempDir::new("write-retained-os-error");
        let out = dir.join("pokeemerald.pack");

        let err = write_new_with(&out, |file| {
            use std::io::Write as _;
            file.write_all(b"half a ")?;
            Err(std::io::Error::from_raw_os_error(OS_ERROR))
        })
        .unwrap_err()
        .at(&out);

        let ImportError::WriteFailed {
            partial, source, ..
        } = &err
        else {
            panic!("a failed write is a write failure: {err:?}");
        };
        assert!(matches!(partial, PartialFile::MayRemain), "{partial:?}");
        assert_eq!(
            source.raw_os_error(),
            Some(OS_ERROR),
            "matching the variant must still reach the OS error number: {err}"
        );
        assert_eq!(
            std::error::Error::source(&err)
                .expect("`WriteFailed` has a source")
                .downcast_ref::<std::io::Error>()
                .expect("and it is the I/O failure itself")
                .raw_os_error(),
            Some(OS_ERROR),
            "and so must `Error::source`, which is what a caller that does \
             not match the variant reaches for"
        );
        assert!(
            err.to_string().contains("a partial file may remain there"),
            "the finding still reaches the caller: {err}"
        );
    }

    #[test]
    fn a_refused_create_reaches_the_caller_as_the_real_os_refusal() {
        // The same boundary for an error the OS itself raised rather than
        // one the test injected: a refused exclusive create carries a real
        // `raw_os_error`, so there is a number there to be lost.
        let dir = TempDir::new("write-refused-os-error");
        let out = dir.join("pokeemerald.pack");
        std::fs::write(&out, b"not the importer's").expect("the existing file writes");

        let err = write_new(&out, b"pack bytes").unwrap_err().at(&out);

        let ImportError::WriteFailed {
            partial, source, ..
        } = &err
        else {
            panic!("a refused create is a write failure: {err:?}");
        };
        assert_eq!(source.kind(), std::io::ErrorKind::AlreadyExists, "{err}");
        assert!(
            source.raw_os_error().is_some(),
            "the OS refusal must arrive with its own error number: {source:?}"
        );
        assert!(
            matches!(partial, PartialFile::Gone),
            "a create that never happened leaves nothing of the importer's: {partial:?}"
        );
    }

    #[test]
    #[cfg(unix)]
    fn a_symlinked_destination_is_refused_and_its_target_survives() {
        // The attack this closes: in a pack directory another account can
        // write to, a link planted at the temporary file's name would send
        // `fs::write`'s truncation at a file of the player's. Exclusive
        // creation refuses the link instead of following it.
        let dir = TempDir::new("write-link");
        let victim = dir.join("player-save.sav");
        std::fs::write(&victim, b"the player's save").expect("the victim writes");
        let planted = dir.join(".pokeemerald.pack.1234.tmp");
        std::os::unix::fs::symlink(&victim, &planted).expect("the planted link");

        let err = write_new(&planted, b"pack bytes").unwrap_err();
        assert_eq!(
            err.source.kind(),
            std::io::ErrorKind::AlreadyExists,
            "{:?}",
            err.source
        );
        assert_eq!(
            std::fs::read(&victim).expect("the victim survives"),
            b"the player's save",
            "the link's target must be byte-identical after a refused write"
        );
    }

    #[test]
    fn a_report_reads_back_what_it_recorded() {
        let report = ImportReport::new(PathBuf::from("/tmp/a.pack"), "fixture", 3, 128);
        assert_eq!(report.pack_path(), Path::new("/tmp/a.pack"));
        assert_eq!(report.profile(), "fixture");
        assert_eq!(report.entry_count(), 3);
        assert_eq!(report.pack_bytes(), 128);
    }
}
