//! Rendering a located profile as the Rust module `rom-import` ships.
//!
//! The output is one `const` and nothing else, so the shipped importer pays
//! no run-time cost for it and a reviewer can diff two generations line by
//! line. Records are written one per line and the `const` carries
//! `#[rustfmt::skip]`: left to itself `rustfmt` would explode a few hundred
//! dense records into a few thousand lines, and a table nobody can scan is
//! a table nobody checks.

use std::fmt::Write as _;

use rom_import::Encoding;

use super::plan::{
    BlobPlan, ImagePlan, MapLayoutPlan, PalettePlan, ProfilePlan, TileAnimPlan, TilesetPlan,
};

/// Render the whole module, ready to write to
/// `crates/rom-import/src/profiles/bpee_rev0.rs`.
pub fn module(plan: &ProfilePlan, sha1: &str, root_count: usize) -> String {
    let mut out = String::with_capacity(64 * 1024);
    let _ = writeln!(
        out,
        "//! Pokemon Emerald (US) rev 0: every ROM address the importer reads.
//!
//! Generated by `cargo xtask gen-rom-profile --rom <rom>` from the build
//! whose whole-file SHA-1 is `{sha1}`. {root_count} roots, each matched
//! against the pack `cargo xtask extract` produces and asserted unique.
//!
//! Do not edit by hand. An address here is only trustworthy because a
//! machine derived and checked it; change the generator and regenerate.

use crate::reader::GbaPtr;
use crate::roots::{{
    AudioRoots, BlobRoot, Encoding, FontRoot, ImageRoot, InterfaceRoots, KeysplitRoot,
    MapLayoutRoot, PaletteRoot, Roots, SampleRoot, SongRoot, SpriteRoots, TextWindowRoots,
    TileAnimRoot, TilesetRoot, TitleScreenRoots, VoicegroupRoot,
}};

/// Pokemon Emerald (US) rev 0's root table.
#[rustfmt::skip]
pub const EMERALD_US_REV0_ROOTS: Roots = Roots {{"
    );

    let _ = writeln!(out, "    tilesets: &[");
    for tileset in &plan.tilesets {
        tileset_root(&mut out, tileset);
    }
    let _ = writeln!(out, "    ],");

    title_screen_roots(&mut out, plan);
    sprite_roots(&mut out, plan);

    let _ = writeln!(out, "    layouts: &[");
    for layout in &plan.layouts {
        layout_root(&mut out, layout);
    }
    let _ = writeln!(out, "    ],");

    let _ = writeln!(out, "    fonts: &[");
    for font in &plan.fonts {
        let _ = writeln!(
            out,
            "        FontRoot {{ id: {:?}, addr: {}, len: {}, width: {}, height: {}, bit_depth: {} }},",
            font.id,
            ptr(font.addr),
            font.len,
            font.width,
            font.height,
            font.bit_depth
        );
    }
    let _ = writeln!(out, "    ],");

    text_window_roots(&mut out, plan);

    let _ = writeln!(out, "    interface: InterfaceRoots {{");
    palette_slice(&mut out, "        ", &plan.interface);
    let _ = writeln!(out, "    }},");

    audio_roots(&mut out, plan);

    let _ = writeln!(out, "}};");
    out
}

/// Render a `palettes: &[..]` field at `indent`.
fn palette_slice(out: &mut String, indent: &str, palettes: &[PalettePlan]) {
    let _ = writeln!(out, "{indent}palettes: &[");
    for palette in palettes {
        let _ = writeln!(out, "{indent}    {},", palette_root(palette));
    }
    let _ = writeln!(out, "{indent}],");
}

/// Render an `images: &[..]`-shaped field at `indent`.
fn image_slice(out: &mut String, indent: &str, field: &str, images: &[ImagePlan]) {
    let _ = writeln!(out, "{indent}{field}: &[");
    for image in images {
        let _ = writeln!(out, "{indent}    {},", image_root(image));
    }
    let _ = writeln!(out, "{indent}],");
}

/// Render the title screen.
fn title_screen_roots(out: &mut String, plan: &ProfilePlan) {
    let title = &plan.title_screen;
    let _ = writeln!(out, "    title_screen: TitleScreenRoots {{");
    image_slice(out, "        ", "images", &title.images);
    let _ = writeln!(out, "        tilemaps: &[");
    for blob in &title.tilemaps {
        let _ = writeln!(out, "            {},", blob_root(blob));
    }
    let _ = writeln!(out, "        ],");
    palette_slice(out, "        ", &title.palettes);
    let _ = writeln!(out, "        bg_palettes: {},", ptr(title.bg_palettes));
    let _ = writeln!(out, "    }},");
}

/// Render the object-event sprites.
fn sprite_roots(out: &mut String, plan: &ProfilePlan) {
    let sprites = &plan.sprites;
    let _ = writeln!(out, "    sprites: SpriteRoots {{");
    let _ = writeln!(
        out,
        "        palette_table: {},",
        ptr(sprites.palette_table)
    );
    image_slice(out, "        ", "sheets", &sprites.sheets);
    palette_slice(out, "        ", &sprites.palettes);
    let _ = writeln!(out, "    }},");
}

/// Render the text-window domain.
fn text_window_roots(out: &mut String, plan: &ProfilePlan) {
    let text_window = &plan.text_window;
    let _ = writeln!(out, "    text_window: TextWindowRoots {{");
    image_slice(out, "        ", "images", &text_window.images);
    palette_slice(out, "        ", &text_window.palettes);
    let _ = writeln!(
        out,
        "        window_palettes: {},",
        ptr(text_window.window_palettes)
    );
    let _ = writeln!(out, "    }},");
}

/// Render the audio domain.
fn audio_roots(out: &mut String, plan: &ProfilePlan) {
    let audio = &plan.audio;
    let _ = writeln!(out, "    audio: AudioRoots {{");
    let _ = writeln!(out, "        song_table: {},", ptr(audio.song_table));
    let _ = writeln!(out, "        songs: &[");
    for song in &audio.songs {
        let _ = writeln!(
            out,
            "            SongRoot {{ id: {:?}, index: {}, header: {}, track_count: {}, voicegroup: {} }},",
            song.id,
            song.index,
            ptr(song.header),
            song.track_count,
            ptr(song.voicegroup)
        );
    }
    let _ = writeln!(out, "        ],");
    let _ = writeln!(out, "        voicegroups: &[");
    for group in &audio.voicegroups {
        let _ = writeln!(
            out,
            "            VoicegroupRoot {{ id: {:?}, label: {:?}, addr: {}, starting_note: {}, declared_slots: {}, addressable_slots: 128 }},",
            group.id,
            group.label,
            ptr(group.addr),
            group.starting_note,
            group.declared_slots
        );
    }
    let _ = writeln!(out, "        ],");
    let _ = writeln!(out, "        keysplits: &[");
    for split in &audio.keysplits {
        let _ = writeln!(
            out,
            "            KeysplitRoot {{ label: {:?}, addr: {}, starting_note: {}, len: {} }},",
            split.label,
            ptr(split.addr),
            split.starting_note,
            split.len
        );
    }
    let _ = writeln!(out, "        ],");
    for (field, samples) in [
        ("direct_sound", &audio.direct_sound),
        ("programmable_wave", &audio.programmable_wave),
    ] {
        let _ = writeln!(out, "        {field}: &[");
        for sample in samples {
            let _ = writeln!(
                out,
                "            SampleRoot {{ id: {:?}, addr: {}, header_len: {}, data_len: {} }},",
                sample.id,
                ptr(sample.addr),
                sample.header_len,
                sample.data_len
            );
        }
        let _ = writeln!(out, "        ],");
    }
    let _ = writeln!(out, "    }},");
}

/// Render one tileset and everything under it.
fn tileset_root(out: &mut String, tileset: &TilesetPlan) {
    let _ = writeln!(out, "        TilesetRoot {{");
    let _ = writeln!(out, "            name: {:?},", tileset.name);
    let _ = writeln!(
        out,
        "            struct_addr: {}, is_compressed: {}, is_secondary: {},",
        ptr(tileset.struct_addr),
        tileset.is_compressed,
        tileset.is_secondary
    );
    let _ = writeln!(out, "            tiles: {},", image_root(&tileset.tiles));
    palette_slice(out, "            ", &tileset.palettes);
    let _ = writeln!(
        out,
        "            metatiles: {},",
        blob_root(&tileset.metatiles)
    );
    let _ = writeln!(
        out,
        "            metatile_attributes: {},",
        blob_root(&tileset.metatile_attributes)
    );
    let _ = writeln!(out, "            callback: {},", hex32(tileset.callback));
    let _ = writeln!(out, "            anims: &[");
    for anim in &tileset.anims {
        tile_anim_root(out, anim);
    }
    let _ = writeln!(out, "            ],");
    let _ = writeln!(out, "        }},");
}

/// Render one tileset animation.
fn tile_anim_root(out: &mut String, anim: &TileAnimPlan) {
    let _ = writeln!(
        out,
        "                TileAnimRoot {{ name: {:?}, frames: &[",
        anim.name
    );
    for frame in &anim.frames {
        let _ = writeln!(out, "                    {},", image_root(frame));
    }
    let _ = writeln!(out, "                ] }},");
}

/// Render one map layout.
fn layout_root(out: &mut String, layout: &MapLayoutPlan) {
    let _ = writeln!(out, "        MapLayoutRoot {{");
    let _ = writeln!(
        out,
        "            name: {:?}, struct_addr: {}, width: {}, height: {},",
        layout.name,
        ptr(layout.struct_addr),
        layout.width,
        layout.height
    );
    let _ = writeln!(out, "            map: {},", blob_root(&layout.map));
    let _ = writeln!(out, "            border: {},", blob_root(&layout.border));
    let _ = writeln!(
        out,
        "            primary_tileset: {}, secondary_tileset: {},",
        ptr(layout.primary_tileset),
        ptr(layout.secondary_tileset)
    );
    let _ = writeln!(out, "        }},");
}

/// Render one image root as a single expression.
fn image_root(image: &ImagePlan) -> String {
    format!(
        "ImageRoot {{ id: {:?}, addr: {}, encoding: {}, rom_bit_depth: {}, pack_bit_depth: {}, width: {}, height: {}, metatile_width: {}, metatile_height: {}, tile_count: {} }}",
        image.id,
        ptr(image.addr),
        encoding(image.encoding),
        image.rom_bit_depth,
        image.pack_bit_depth,
        image.width,
        image.height,
        image.metatile_width,
        image.metatile_height,
        image.tile_count
    )
}

/// Render one palette root as a single expression.
fn palette_root(palette: &PalettePlan) -> String {
    format!(
        "PaletteRoot {{ id: {:?}, addr: {}, color_count: {} }}",
        palette.id,
        ptr(palette.addr),
        palette.color_count
    )
}

/// Render one blob root as a single expression.
fn blob_root(blob: &BlobPlan) -> String {
    format!(
        "BlobRoot {{ id: {:?}, addr: {}, encoding: {}, len: {} }}",
        blob.id,
        ptr(blob.addr),
        encoding(blob.encoding),
        blob.len
    )
}

/// Render a `GbaPtr` constructor.
fn ptr(addr: u32) -> String {
    format!("GbaPtr::at({})", hex32(addr))
}

/// Render a 32-bit value as `0xHHHH_HHHH`, the separated form
/// `clippy::unreadable_literal` requires.
fn hex32(value: u32) -> String {
    format!("0x{:04X}_{:04X}", value >> 16, value & 0xFFFF)
}

/// Render an [`Encoding`] variant.
fn encoding(encoding: Encoding) -> &'static str {
    match encoding {
        Encoding::Raw => "Encoding::Raw",
        Encoding::Lz77 => "Encoding::Lz77",
    }
}

#[cfg(test)]
mod tests {
    use super::{blob_root, encoding, hex32, image_root, palette_root, ptr};
    use crate::gen_rom_profile::plan::{BlobPlan, ImagePlan, PalettePlan};
    use rom_import::Encoding;

    #[test]
    fn addresses_render_as_padded_hex_constructors() {
        assert_eq!(ptr(0x083D_F704), "GbaPtr::at(0x083D_F704)");
        assert_eq!(ptr(0), "GbaPtr::at(0x0000_0000)");
        assert_eq!(hex32(0xDEAD_BEEF), "0xDEAD_BEEF");
    }

    #[test]
    fn every_encoding_has_a_path() {
        assert_eq!(encoding(Encoding::Raw), "Encoding::Raw");
        assert_eq!(encoding(Encoding::Lz77), "Encoding::Lz77");
    }

    #[test]
    fn records_render_on_one_line() {
        let image = image_root(&ImagePlan {
            id: "tileset/general/tiles".to_owned(),
            addr: 0x08DD_5010,
            encoding: Encoding::Lz77,
            rom_bit_depth: 4,
            pack_bit_depth: 4,
            width: 128,
            height: 256,
            metatile_width: 1,
            metatile_height: 1,
            tile_count: 512,
        });
        assert!(!image.contains('\n'), "{image}");
        assert!(image.contains("GbaPtr::at(0x08DD_5010)"), "{image}");
        assert!(image.contains("tile_count: 512"), "{image}");

        let palette = palette_root(&PalettePlan {
            id: "title/palette/pokemon_logo".to_owned(),
            addr: 0x08DD_E258,
            color_count: 224,
        });
        assert!(!palette.contains('\n'), "{palette}");
        assert!(palette.contains("color_count: 224"), "{palette}");

        let blob = blob_root(&BlobPlan {
            id: "layout/route103/map".to_owned(),
            addr: 0x083E_C474,
            encoding: Encoding::Raw,
            len: 3520,
        });
        assert!(!blob.contains('\n'), "{blob}");
        assert!(blob.contains("len: 3520"), "{blob}");
    }
}
